"""
Pydantic v2 models for chuk-mcp-maritime-archives.

Domain models (extra="allow") live in maritime.py.
Response envelopes (extra="forbid") live in responses.py.
"""

from .maritime import (
    CargoSummary,
    HullHydrodynamics,
    HullProfile,
    Incident,
    PersonnelSummary,
    Position,
    PositionUncertainty,
    SinkingCharacteristics,
    SourceReference,
    Vessel,
    VesselDimensions,
    Waypoint,
)
from .responses import (
    ArchiveDetailResponse,
    ArchiveInfo,
    ArchiveListResponse,
    CapabilitiesResponse,
    CargoDetailResponse,
    CargoInfo,
    CargoSearchResponse,
    CrewDetailResponse,
    CrewInfo,
    CrewSearchResponse,
    ErrorResponse,
    GeoJSONExportResponse,
    HullProfileListResponse,
    HullProfileResponse,
    LocationDetailResponse,
    LocationInfo,
    LocationSearchResponse,
    PositionAssessmentResponse,
    PositionEstimateResponse,
    RouteDetailResponse,
    RouteInfo,
    RouteListResponse,
    RouteWaypointInfo,
    StatisticsResponse,
    ToolInfo,
    VesselDetailResponse,
    VesselInfo,
    VesselSearchResponse,
    VoyageDetailResponse,
    VoyageInfo,
    VoyageSearchResponse,
    WreckDetailResponse,
    WreckInfo,
    WreckSearchResponse,
    format_response,
)

__all__ = [
    # Domain models
    "CargoSummary",
    "HullHydrodynamics",
    "HullProfile",
    "Incident",
    "PersonnelSummary",
    "Position",
    "PositionUncertainty",
    "SinkingCharacteristics",
    "SourceReference",
    "Vessel",
    "VesselDimensions",
    "Waypoint",
    # Response models
    "ArchiveDetailResponse",
    "ArchiveInfo",
    "ArchiveListResponse",
    "CapabilitiesResponse",
    "CargoDetailResponse",
    "CargoInfo",
    "CargoSearchResponse",
    "CrewDetailResponse",
    "CrewInfo",
    "CrewSearchResponse",
    "ErrorResponse",
    "GeoJSONExportResponse",
    "HullProfileListResponse",
    "HullProfileResponse",
    "LocationDetailResponse",
    "LocationInfo",
    "LocationSearchResponse",
    "PositionAssessmentResponse",
    "PositionEstimateResponse",
    "RouteDetailResponse",
    "RouteInfo",
    "RouteListResponse",
    "RouteWaypointInfo",
    "StatisticsResponse",
    "ToolInfo",
    "VesselDetailResponse",
    "VesselInfo",
    "VesselSearchResponse",
    "VoyageDetailResponse",
    "VoyageInfo",
    "VoyageSearchResponse",
    "WreckDetailResponse",
    "WreckInfo",
    "WreckSearchResponse",
    "format_response",
]
