"""
Hull hydrodynamic profiles for VOC ship types.

Reference data for drift modelling. Values derived from archaeological
measurements of recovered VOC wrecks and construction specifications.

Data is loaded from ``data/hull_profiles.json`` (generated by
``scripts/generate_reference.py``).
"""

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

_DEFAULT_DATA_DIR = Path(__file__).resolve().parent.parent.parent.parent / "data"

HULL_PROFILES: dict[str, dict] = {}


def _load_hull_profiles(data_dir: Path | None = None) -> dict[str, dict]:
    """Load hull profiles from JSON file, keyed by ship_type."""
    global HULL_PROFILES
    if HULL_PROFILES:
        return HULL_PROFILES

    path = (data_dir or _DEFAULT_DATA_DIR) / "hull_profiles.json"
    if not path.exists():
        logger.warning("Hull profiles not found: %s (run scripts/generate_reference.py)", path)
        return HULL_PROFILES

    with open(path) as f:
        profiles = json.load(f)

    for profile in profiles:
        ship_type = profile.get("ship_type", "")
        if ship_type:
            HULL_PROFILES[ship_type] = profile

    logger.info("Loaded %d hull profiles from %s", len(HULL_PROFILES), path.name)
    return HULL_PROFILES


# Load on import
_load_hull_profiles()
