"""
Speed Profiles — historical sailing speed statistics from CLIWOC data.

Pre-computed speed profiles per route segment, derived from CLIWOC 2.1
daily positions. Each profile gives mean, median, standard deviation,
and percentile speeds (km/day) for a route segment, optionally broken
down by departure month for seasonal variation.

Data is loaded from ``data/speed_profiles.json`` (generated by
``scripts/generate_speed_profiles.py``).
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_DEFAULT_DATA_DIR = Path(__file__).resolve().parent.parent.parent.parent / "data"

# Loaded from JSON: list of profile dicts
_PROFILES: list[dict[str, Any]] = []

# Indexes: route_id -> [profile dicts]
_PROFILES_BY_ROUTE: dict[str, list[dict[str, Any]]] = {}


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------


def _load_speed_profiles(data_dir: Path | None = None) -> None:
    """Load speed profile data from JSON file."""
    global _PROFILES, _PROFILES_BY_ROUTE
    if _PROFILES:
        return

    path = (data_dir or _DEFAULT_DATA_DIR) / "speed_profiles.json"
    if not path.exists():
        logger.warning(
            "Speed profiles not found: %s (run scripts/generate_speed_profiles.py)",
            path,
        )
        return

    with open(path) as f:
        data = json.load(f)

    _PROFILES = data.get("profiles", [])

    # Build route index
    for profile in _PROFILES:
        route_id = profile["route_id"]
        if route_id not in _PROFILES_BY_ROUTE:
            _PROFILES_BY_ROUTE[route_id] = []
        _PROFILES_BY_ROUTE[route_id].append(profile)

    logger.info("Loaded %d speed profiles from %s", len(_PROFILES), path.name)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def get_speed_profile(
    route_id: str,
    departure_month: int | None = None,
) -> list[dict[str, Any]]:
    """
    Return all segment speed profiles for a route.

    If departure_month is given, returns month-specific profiles where
    available, falling back to all-months aggregates.

    Args:
        route_id: Route identifier (e.g., "outward_outer")
        departure_month: Optional month (1-12) for seasonal data

    Returns:
        List of segment profile dicts, or empty list if route not found.
    """
    _load_speed_profiles()
    route_profiles = _PROFILES_BY_ROUTE.get(route_id, [])
    if not route_profiles:
        return []

    if departure_month is None:
        # Return all-months aggregates (departure_month is null)
        return [p for p in route_profiles if p.get("departure_month") is None]

    # Try month-specific first, fall back to all-months per segment
    month_profiles = [p for p in route_profiles if p.get("departure_month") == departure_month]
    all_months = [p for p in route_profiles if p.get("departure_month") is None]

    if not month_profiles:
        return all_months

    # Fill in any segments missing from month data with all-months data
    month_segments = {(p["segment_from"], p["segment_to"]) for p in month_profiles}
    for p in all_months:
        key = (p["segment_from"], p["segment_to"])
        if key not in month_segments:
            month_profiles.append(p)

    return month_profiles


def get_segment_speed(
    route_id: str,
    segment_from: str,
    segment_to: str,
    departure_month: int | None = None,
) -> dict[str, Any] | None:
    """
    Look up speed data for a single route segment.

    Falls back from month-specific to all-months if needed.
    """
    _load_speed_profiles()
    route_profiles = _PROFILES_BY_ROUTE.get(route_id, [])
    if not route_profiles:
        return None

    # Try month-specific first
    if departure_month is not None:
        for p in route_profiles:
            if (
                p["segment_from"] == segment_from
                and p["segment_to"] == segment_to
                and p.get("departure_month") == departure_month
            ):
                return p

    # Fall back to all-months
    for p in route_profiles:
        if (
            p["segment_from"] == segment_from
            and p["segment_to"] == segment_to
            and p.get("departure_month") is None
        ):
            return p

    return None


def list_profiled_routes() -> list[str]:
    """Return route IDs that have speed profile data."""
    _load_speed_profiles()
    return sorted(_PROFILES_BY_ROUTE.keys())


# Load on import
_load_speed_profiles()
