#!/usr/bin/env python3
"""
Generate curated VOC cargo manifest entries.

The Dutch East India Company (VOC, 1602-1799) was the world's first
multinational corporation and dominated the spice trade for nearly two
centuries. Its ships carried pepper, nutmeg, mace, cloves, cinnamon,
textiles, porcelain, tea, coffee, and silver between Asia and Amsterdam.

Outputs:
    data/cargo.json  -- ~200 cargo manifest records (voc_cargo:000001 .. voc_cargo:000200)

Sources: Dutch-Asiatic Shipping (DAS) database, VOC Opvarenden database,
Glamann "Dutch-Asiatic Trade 1620-1740" (1981), Gaastra "The Dutch East
India Company" (2003), Bruijn/Gaastra/Schoffer "Dutch-Asiatic Shipping
in the 17th and 18th Centuries" (1987).

Run from the project root:

    python scripts/generate_cargo.py
"""

import json
from pathlib import Path

from download_utils import is_cached, parse_args

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"

OUTPUT = DATA_DIR / "cargo.json"

# ---------------------------------------------------------------------------
# Cargo data -- ~200 curated VOC cargo manifest entries (1700-1795)
# ---------------------------------------------------------------------------
# Each tuple: (id, voyage_id, commodity, commodity_dutch, quantity,
#               quantity_kg, origin, destination, date, value_guilders, notes)
CARGO_RAW = [
    # -----------------------------------------------------------------------
    # PEPPER (~30 records) -- The single most important VOC commodity
    # -----------------------------------------------------------------------
    (
        1,
        "das:4012",
        "pepper",
        "peper",
        "450 balen",
        27000,
        "Batavia",
        "Amsterdam",
        "1700-03-15",
        187500,
        "Black Malabar pepper, premium grade",
    ),
    (
        2,
        "das:4055",
        "pepper",
        "peper",
        "380 balen",
        22800,
        "Cochin",
        "Amsterdam",
        "1702-04-22",
        152000,
        "Malabar coast pepper, first quality",
    ),
    (
        3,
        "das:4101",
        "pepper",
        "peper",
        "520 balen",
        31200,
        "Bantam",
        "Amsterdam",
        "1704-02-10",
        208000,
        "Bantam black pepper, standard grade",
    ),
    (
        4,
        "das:4178",
        "pepper",
        "peper",
        "600 balen",
        36000,
        "Batavia",
        "Amsterdam",
        "1706-03-18",
        240000,
        "Mixed Sumatran and Javanese pepper",
    ),
    (
        5,
        "das:4230",
        "pepper",
        "peper",
        "310 balen",
        18600,
        "Malabar",
        "Amsterdam",
        "1708-05-12",
        139500,
        "White Malabar pepper, scarce commodity",
    ),
    (
        6,
        "das:4312",
        "pepper",
        "peper",
        "480 balen",
        28800,
        "Batavia",
        "Amsterdam",
        "1710-04-08",
        192000,
        "Black pepper from Sumatran west coast",
    ),
    (
        7,
        "das:4401",
        "pepper",
        "peper",
        "550 balen",
        33000,
        "Cochin",
        "Amsterdam",
        "1712-03-25",
        247500,
        "Premium Malabar pepper, large grain",
    ),
    (
        8,
        "das:4489",
        "pepper",
        "peper",
        "420 balen",
        25200,
        "Bantam",
        "Amsterdam",
        "1714-02-14",
        168000,
        "Bantam pepper, moderate quality",
    ),
    (
        9,
        "das:4567",
        "pepper",
        "peper",
        "370 balen",
        22200,
        "Batavia",
        "Amsterdam",
        "1716-04-30",
        148000,
        "Sumatran Lampong pepper",
    ),
    (
        10,
        "das:4634",
        "pepper",
        "peper",
        "500 balen",
        30000,
        "Malabar",
        "Amsterdam",
        "1718-03-22",
        225000,
        "Fine Malabar pepper, well dried",
    ),
    (
        11,
        "das:4721",
        "pepper",
        "peper",
        "460 balen",
        27600,
        "Batavia",
        "Amsterdam",
        "1720-05-10",
        184000,
        "Mixed Asian pepper cargo",
    ),
    (
        12,
        "das:4812",
        "pepper",
        "peper",
        "390 balen",
        23400,
        "Cochin",
        "Amsterdam",
        "1722-04-15",
        175500,
        "Cochin pepper, excellent condition",
    ),
    (
        13,
        "das:4901",
        "pepper",
        "peper",
        "580 balen",
        34800,
        "Batavia",
        "Amsterdam",
        "1725-03-08",
        232000,
        "Bulk pepper shipment from Batavia warehouse",
    ),
    (
        14,
        "das:4989",
        "pepper",
        "peper",
        "350 balen",
        21000,
        "Bantam",
        "Amsterdam",
        "1728-02-20",
        157500,
        "Bantam pepper, slightly damp",
    ),
    (
        15,
        "das:5078",
        "pepper",
        "peper",
        "440 balen",
        26400,
        "Malabar",
        "Amsterdam",
        "1730-04-12",
        198000,
        "Tellicherry pepper, premium",
    ),
    (
        16,
        "das:5167",
        "pepper",
        "peper",
        "510 balen",
        30600,
        "Batavia",
        "Amsterdam",
        "1733-03-18",
        204000,
        "Lampong district pepper",
    ),
    (
        17,
        "das:5256",
        "pepper",
        "peper",
        "470 balen",
        28200,
        "Cochin",
        "Amsterdam",
        "1735-05-22",
        211500,
        "Malabar pepper, double-sifted",
    ),
    (
        18,
        "das:5345",
        "pepper",
        "peper",
        "290 balen",
        17400,
        "Batavia",
        "Amsterdam",
        "1738-02-14",
        130500,
        "Java pepper, lower grade",
    ),
    (
        19,
        "das:5434",
        "pepper",
        "peper",
        "530 balen",
        31800,
        "Malabar",
        "Amsterdam",
        "1740-04-08",
        238500,
        "Premium Calicut pepper",
    ),
    (
        20,
        "das:5523",
        "pepper",
        "peper",
        "410 balen",
        24600,
        "Batavia",
        "Amsterdam",
        "1743-03-25",
        164000,
        "Sumatran west coast pepper",
    ),
    (
        21,
        "das:5612",
        "pepper",
        "peper",
        "360 balen",
        21600,
        "Cochin",
        "Amsterdam",
        "1746-05-12",
        162000,
        "Cochin factory pepper",
    ),
    (
        22,
        "das:5701",
        "pepper",
        "peper",
        "490 balen",
        29400,
        "Batavia",
        "Amsterdam",
        "1749-02-18",
        196000,
        "Lampong black pepper",
    ),
    (
        23,
        "das:5790",
        "pepper",
        "peper",
        "320 balen",
        19200,
        "Malabar",
        "Amsterdam",
        "1752-04-30",
        144000,
        "Malabar pepper, fair quality",
    ),
    (
        24,
        "das:5879",
        "pepper",
        "peper",
        "560 balen",
        33600,
        "Batavia",
        "Amsterdam",
        "1755-03-22",
        224000,
        "Large Batavia pepper consignment",
    ),
    (
        25,
        "das:5968",
        "pepper",
        "peper",
        "430 balen",
        25800,
        "Bantam",
        "Amsterdam",
        "1758-05-10",
        172000,
        "Bantam pepper, well preserved",
    ),
    (
        26,
        "das:6057",
        "pepper",
        "peper",
        "380 balen",
        22800,
        "Batavia",
        "Amsterdam",
        "1762-02-14",
        152000,
        "Java and Sumatra mixed pepper",
    ),
    (
        27,
        "das:6146",
        "pepper",
        "peper",
        "450 balen",
        27000,
        "Malabar",
        "Amsterdam",
        "1768-04-08",
        202500,
        "Tellicherry fine pepper",
    ),
    (
        28,
        "das:6235",
        "pepper",
        "peper",
        "340 balen",
        20400,
        "Batavia",
        "Amsterdam",
        "1774-03-18",
        153000,
        "Declining pepper trade, reduced cargo",
    ),
    (
        29,
        "das:6324",
        "pepper",
        "peper",
        "280 balen",
        16800,
        "Cochin",
        "Amsterdam",
        "1780-05-22",
        126000,
        "Wartime pepper shipment, Fourth Anglo-Dutch War",
    ),
    (
        30,
        "das:6413",
        "pepper",
        "peper",
        "200 balen",
        12000,
        "Batavia",
        "Amsterdam",
        "1790-02-10",
        90000,
        "Late VOC pepper cargo, reduced volumes",
    ),
    # -----------------------------------------------------------------------
    # NUTMEG & MACE (~25 records) -- VOC monopoly from Banda Islands
    # -----------------------------------------------------------------------
    (
        31,
        "das:4023",
        "nutmeg",
        "nootmuskaat",
        "150 picul",
        9000,
        "Banda",
        "Amsterdam",
        "1700-04-20",
        60000,
        "Banda Islands nutmeg, VOC monopoly product",
    ),
    (
        32,
        "das:4089",
        "mace",
        "foelie",
        "80 picul",
        4800,
        "Banda",
        "Amsterdam",
        "1702-05-15",
        64000,
        "Scarlet mace from Banda, highest grade",
    ),
    (
        33,
        "das:4145",
        "nutmeg",
        "nootmuskaat",
        "200 picul",
        12000,
        "Banda",
        "Amsterdam",
        "1705-03-12",
        80000,
        "Large nutmeg shipment, good harvest year",
    ),
    (
        34,
        "das:4210",
        "mace",
        "foelie",
        "60 picul",
        3600,
        "Banda",
        "Amsterdam",
        "1707-04-28",
        48000,
        "Premium foelie, bright orange colour",
    ),
    (
        35,
        "das:4298",
        "nutmeg",
        "nootmuskaat",
        "180 picul",
        10800,
        "Amboina",
        "Amsterdam",
        "1710-02-18",
        72000,
        "Ambon-sourced nutmeg via Banda",
    ),
    (
        36,
        "das:4378",
        "mace",
        "foelie",
        "90 picul",
        5400,
        "Banda",
        "Amsterdam",
        "1712-05-08",
        72000,
        "Extra-fine foelie for Amsterdam spice auctions",
    ),
    (
        37,
        "das:4456",
        "nutmeg",
        "nootmuskaat",
        "170 picul",
        10200,
        "Banda",
        "Amsterdam",
        "1715-03-22",
        68000,
        "Standard nutmeg harvest consignment",
    ),
    (
        38,
        "das:4545",
        "mace",
        "foelie",
        "70 picul",
        4200,
        "Banda",
        "Amsterdam",
        "1718-04-14",
        56000,
        "Select foelie for European markets",
    ),
    (
        39,
        "das:4623",
        "nutmeg",
        "nootmuskaat",
        "190 picul",
        11400,
        "Banda",
        "Amsterdam",
        "1720-02-28",
        76000,
        "Banda nutmeg, carefully dried and sorted",
    ),
    (
        40,
        "das:4712",
        "mace",
        "foelie",
        "100 picul",
        6000,
        "Banda",
        "Amsterdam",
        "1723-05-18",
        80000,
        "Large mace consignment for re-export",
    ),
    (
        41,
        "das:4800",
        "nutmeg",
        "nootmuskaat",
        "160 picul",
        9600,
        "Banda",
        "Amsterdam",
        "1726-03-10",
        64000,
        "Routine Banda nutmeg supply",
    ),
    (
        42,
        "das:4890",
        "mace",
        "foelie",
        "75 picul",
        4500,
        "Banda",
        "Amsterdam",
        "1729-04-22",
        60000,
        "Premium mace, fragrant and well cured",
    ),
    (
        43,
        "das:4978",
        "nutmeg",
        "nootmuskaat",
        "140 picul",
        8400,
        "Banda",
        "Amsterdam",
        "1732-02-15",
        56000,
        "Nutmeg from new Banda plantations",
    ),
    (
        44,
        "das:5067",
        "mace",
        "foelie",
        "85 picul",
        5100,
        "Banda",
        "Amsterdam",
        "1735-03-28",
        68000,
        "High-quality Banda mace",
    ),
    (
        45,
        "das:5156",
        "nutmeg",
        "nootmuskaat",
        "130 picul",
        7800,
        "Banda",
        "Amsterdam",
        "1738-05-12",
        52000,
        "Reduced nutmeg production this year",
    ),
    (
        46,
        "das:5245",
        "mace",
        "foelie",
        "65 picul",
        3900,
        "Banda",
        "Amsterdam",
        "1742-04-08",
        52000,
        "Foelie from perkeniers estates",
    ),
    (
        47,
        "das:5334",
        "nutmeg",
        "nootmuskaat",
        "175 picul",
        10500,
        "Banda",
        "Amsterdam",
        "1745-02-20",
        70000,
        "Good harvest, abundant supply",
    ),
    (
        48,
        "das:5423",
        "mace",
        "foelie",
        "55 picul",
        3300,
        "Banda",
        "Amsterdam",
        "1748-03-15",
        44000,
        "Mace scarce this season",
    ),
    (
        49,
        "das:5512",
        "nutmeg",
        "nootmuskaat",
        "120 picul",
        7200,
        "Banda",
        "Amsterdam",
        "1752-05-22",
        48000,
        "Banda nutmeg, moderate quality",
    ),
    (
        50,
        "das:5601",
        "mace",
        "foelie",
        "95 picul",
        5700,
        "Banda",
        "Amsterdam",
        "1756-04-10",
        76000,
        "Large foelie shipment for European distribution",
    ),
    (
        51,
        "das:5690",
        "nutmeg",
        "nootmuskaat",
        "110 picul",
        6600,
        "Banda",
        "Amsterdam",
        "1762-02-28",
        44000,
        "Banda nutmeg, late season harvest",
    ),
    (
        52,
        "das:5779",
        "mace",
        "foelie",
        "50 picul",
        3000,
        "Banda",
        "Amsterdam",
        "1770-03-18",
        40000,
        "Reduced mace output from aging plantations",
    ),
    (
        53,
        "das:5868",
        "nutmeg",
        "nootmuskaat",
        "100 picul",
        6000,
        "Banda",
        "Amsterdam",
        "1778-04-22",
        40000,
        "Wartime nutmeg shipment",
    ),
    (
        54,
        "das:5957",
        "mace",
        "foelie",
        "45 picul",
        2700,
        "Banda",
        "Amsterdam",
        "1785-02-14",
        36000,
        "Declining Banda mace production",
    ),
    (
        55,
        "das:6046",
        "nutmeg",
        "nootmuskaat",
        "80 picul",
        4800,
        "Banda",
        "Amsterdam",
        "1792-03-10",
        32000,
        "Late VOC era nutmeg, reduced monopoly control",
    ),
    # -----------------------------------------------------------------------
    # CLOVES (~20 records) -- VOC monopoly from Moluccas
    # -----------------------------------------------------------------------
    (
        56,
        "das:4034",
        "cloves",
        "kruidnagelen",
        "200 picul",
        12000,
        "Amboina",
        "Amsterdam",
        "1700-05-18",
        120000,
        "Ambon cloves, VOC monopoly enforced by extirpation policy",
    ),
    (
        57,
        "das:4112",
        "cloves",
        "kruidnagelen",
        "180 picul",
        10800,
        "Amboina",
        "Amsterdam",
        "1703-04-10",
        108000,
        "Premium Ambon cloves, carefully dried",
    ),
    (
        58,
        "das:4189",
        "cloves",
        "kruidnagelen",
        "250 picul",
        15000,
        "Ternate",
        "Amsterdam",
        "1706-02-28",
        150000,
        "Ternate clove harvest, exceptional year",
    ),
    (
        59,
        "das:4267",
        "cloves",
        "kruidnagelen",
        "170 picul",
        10200,
        "Amboina",
        "Amsterdam",
        "1709-03-22",
        102000,
        "Standard Ambon clove consignment",
    ),
    (
        60,
        "das:4345",
        "cloves",
        "kruidnagelen",
        "220 picul",
        13200,
        "Amboina",
        "Amsterdam",
        "1712-05-14",
        132000,
        "Large clove shipment for Amsterdam auctions",
    ),
    (
        61,
        "das:4423",
        "cloves",
        "kruidnagelen",
        "150 picul",
        9000,
        "Ternate",
        "Amsterdam",
        "1715-04-08",
        90000,
        "Ternate cloves, second quality",
    ),
    (
        62,
        "das:4512",
        "cloves",
        "kruidnagelen",
        "300 picul",
        18000,
        "Amboina",
        "Amsterdam",
        "1718-02-20",
        180000,
        "Bumper crop year, maximum shipment",
    ),
    (
        63,
        "das:4590",
        "cloves",
        "kruidnagelen",
        "190 picul",
        11400,
        "Amboina",
        "Amsterdam",
        "1721-03-15",
        114000,
        "Routine annual clove cargo",
    ),
    (
        64,
        "das:4678",
        "cloves",
        "kruidnagelen",
        "160 picul",
        9600,
        "Amboina",
        "Amsterdam",
        "1725-05-22",
        96000,
        "Ambon cloves after hongi expeditions",
    ),
    (
        65,
        "das:4767",
        "cloves",
        "kruidnagelen",
        "280 picul",
        16800,
        "Amboina",
        "Amsterdam",
        "1728-04-10",
        168000,
        "Major clove consignment, strong demand",
    ),
    (
        66,
        "das:4856",
        "cloves",
        "kruidnagelen",
        "140 picul",
        8400,
        "Ternate",
        "Amsterdam",
        "1732-02-18",
        84000,
        "Ternate district cloves",
    ),
    (
        67,
        "das:4945",
        "cloves",
        "kruidnagelen",
        "210 picul",
        12600,
        "Amboina",
        "Amsterdam",
        "1735-03-28",
        126000,
        "High-grade Ambon cloves",
    ),
    (
        68,
        "das:5034",
        "cloves",
        "kruidnagelen",
        "130 picul",
        7800,
        "Amboina",
        "Amsterdam",
        "1740-05-12",
        78000,
        "Moderate harvest, some crop damage",
    ),
    (
        69,
        "das:5123",
        "cloves",
        "kruidnagelen",
        "240 picul",
        14400,
        "Amboina",
        "Amsterdam",
        "1744-04-08",
        144000,
        "Recovery year, strong production",
    ),
    (
        70,
        "das:5212",
        "cloves",
        "kruidnagelen",
        "175 picul",
        10500,
        "Amboina",
        "Amsterdam",
        "1748-02-20",
        105000,
        "Standard Ambon clove delivery",
    ),
    (
        71,
        "das:5301",
        "cloves",
        "kruidnagelen",
        "120 picul",
        7200,
        "Amboina",
        "Amsterdam",
        "1754-03-15",
        72000,
        "Reduced harvest, aging trees",
    ),
    (
        72,
        "das:5390",
        "cloves",
        "kruidnagelen",
        "200 picul",
        12000,
        "Amboina",
        "Amsterdam",
        "1760-05-22",
        120000,
        "Good harvest year for Ambon cloves",
    ),
    (
        73,
        "das:5479",
        "cloves",
        "kruidnagelen",
        "100 picul",
        6000,
        "Amboina",
        "Amsterdam",
        "1768-04-10",
        60000,
        "Declining clove trade, smuggling increasing",
    ),
    (
        74,
        "das:5568",
        "cloves",
        "kruidnagelen",
        "150 picul",
        9000,
        "Amboina",
        "Amsterdam",
        "1776-02-28",
        90000,
        "Wartime clove shipment under convoy",
    ),
    (
        75,
        "das:5657",
        "cloves",
        "kruidnagelen",
        "80 picul",
        4800,
        "Amboina",
        "Amsterdam",
        "1790-03-18",
        48000,
        "Late VOC clove cargo, monopoly weakening",
    ),
    # -----------------------------------------------------------------------
    # CINNAMON (~15 records) -- From Ceylon
    # -----------------------------------------------------------------------
    (
        76,
        "das:4045",
        "cinnamon",
        "kaneel",
        "300 balen",
        18000,
        "Ceylon",
        "Amsterdam",
        "1701-03-22",
        90000,
        "Ceylon cinnamon, peeled by Salagama caste",
    ),
    (
        77,
        "das:4156",
        "cinnamon",
        "kaneel",
        "250 balen",
        15000,
        "Ceylon",
        "Amsterdam",
        "1705-04-18",
        75000,
        "Colombo warehouse cinnamon, first quality",
    ),
    (
        78,
        "das:4256",
        "cinnamon",
        "kaneel",
        "400 balen",
        24000,
        "Ceylon",
        "Amsterdam",
        "1710-02-10",
        120000,
        "Large cinnamon shipment, strong harvest",
    ),
    (
        79,
        "das:4356",
        "cinnamon",
        "kaneel",
        "200 balen",
        12000,
        "Ceylon",
        "Amsterdam",
        "1715-05-08",
        60000,
        "Standard Ceylon cinnamon consignment",
    ),
    (
        80,
        "das:4445",
        "cinnamon",
        "kaneel",
        "350 balen",
        21000,
        "Ceylon",
        "Amsterdam",
        "1720-03-28",
        105000,
        "Fine Ceylon cinnamon for European spice market",
    ),
    (
        81,
        "das:4534",
        "cinnamon",
        "kaneel",
        "280 balen",
        16800,
        "Ceylon",
        "Amsterdam",
        "1725-04-14",
        84000,
        "Galle district cinnamon, well dried",
    ),
    (
        82,
        "das:4623",
        "cinnamon",
        "kaneel",
        "500 balen",
        30000,
        "Ceylon",
        "Amsterdam",
        "1730-02-20",
        150000,
        "Exceptional harvest, maximum cinnamon cargo",
    ),
    (
        83,
        "das:4712",
        "cinnamon",
        "kaneel",
        "320 balen",
        19200,
        "Ceylon",
        "Amsterdam",
        "1735-05-18",
        96000,
        "Colombo cinnamon, premium grade",
    ),
    (
        84,
        "das:4801",
        "cinnamon",
        "kaneel",
        "180 balen",
        10800,
        "Ceylon",
        "Amsterdam",
        "1740-03-10",
        54000,
        "Reduced cinnamon after labour shortages",
    ),
    (
        85,
        "das:4890",
        "cinnamon",
        "kaneel",
        "370 balen",
        22200,
        "Ceylon",
        "Amsterdam",
        "1745-04-22",
        111000,
        "Recovery year, plentiful cinnamon supply",
    ),
    (
        86,
        "das:4979",
        "cinnamon",
        "kaneel",
        "260 balen",
        15600,
        "Ceylon",
        "Amsterdam",
        "1750-02-15",
        78000,
        "Standard Ceylon cinnamon, moderate quality",
    ),
    (
        87,
        "das:5068",
        "cinnamon",
        "kaneel",
        "150 balen",
        9000,
        "Ceylon",
        "Amsterdam",
        "1758-03-28",
        45000,
        "Cinnamon trade declining, competition from cassia",
    ),
    (
        88,
        "das:5157",
        "cinnamon",
        "kaneel",
        "220 balen",
        13200,
        "Ceylon",
        "Amsterdam",
        "1765-05-12",
        66000,
        "Ceylon cinnamon still commands premium price",
    ),
    (
        89,
        "das:5246",
        "cinnamon",
        "kaneel",
        "130 balen",
        7800,
        "Ceylon",
        "Amsterdam",
        "1775-04-08",
        39000,
        "Reduced shipment, British threat to Ceylon",
    ),
    (
        90,
        "das:5335",
        "cinnamon",
        "kaneel",
        "100 balen",
        6000,
        "Ceylon",
        "Amsterdam",
        "1788-02-20",
        30000,
        "Late VOC cinnamon, Ceylon under pressure",
    ),
    # -----------------------------------------------------------------------
    # TEXTILES (~25 records) -- Indian cotton and silk
    # -----------------------------------------------------------------------
    (
        91,
        "das:4056",
        "cotton cloth",
        "katoen",
        "800 stuk",
        4000,
        "Coromandel",
        "Amsterdam",
        "1700-04-10",
        80000,
        "Painted chintz from Pulicat factory",
    ),
    (
        92,
        "das:4123",
        "silk",
        "zijde",
        "120 balen",
        3600,
        "Bengal",
        "Amsterdam",
        "1702-03-28",
        120000,
        "Bengal raw silk, finest quality",
    ),
    (
        93,
        "das:4190",
        "cotton cloth",
        "sits",
        "600 stuk",
        3000,
        "Coromandel",
        "Amsterdam",
        "1704-05-15",
        60000,
        "Chintz fabric for European fashion market",
    ),
    (
        94,
        "das:4268",
        "silk",
        "zijde",
        "80 balen",
        2400,
        "Bengal",
        "Amsterdam",
        "1706-04-22",
        80000,
        "Hooghly silk, lustrous quality",
    ),
    (
        95,
        "das:4346",
        "cotton cloth",
        "katoen",
        "1000 stuk",
        5000,
        "Surat",
        "Amsterdam",
        "1708-02-18",
        100000,
        "Surat calico, bleached white",
    ),
    (
        96,
        "das:4424",
        "silk",
        "zijde",
        "150 balen",
        4500,
        "Bengal",
        "Amsterdam",
        "1710-05-10",
        150000,
        "Large silk consignment from Hooghly factory",
    ),
    (
        97,
        "das:4501",
        "cotton cloth",
        "sits",
        "700 stuk",
        3500,
        "Masulipatnam",
        "Amsterdam",
        "1712-03-22",
        70000,
        "Masulipatnam chintz, elaborate patterns",
    ),
    (
        98,
        "das:4579",
        "silk",
        "zijde",
        "100 balen",
        3000,
        "Bengal",
        "Amsterdam",
        "1714-04-14",
        100000,
        "Bengal silk for Amsterdam textile merchants",
    ),
    (
        99,
        "das:4657",
        "cotton cloth",
        "katoen",
        "900 stuk",
        4500,
        "Coromandel",
        "Amsterdam",
        "1716-02-28",
        90000,
        "Pulicat chintz, floral designs",
    ),
    (
        100,
        "das:4735",
        "silk",
        "zijde",
        "60 balen",
        1800,
        "Bengal",
        "Amsterdam",
        "1718-05-18",
        60000,
        "Select Bengal silk, damaged by monsoon",
    ),
    (
        101,
        "das:4813",
        "cotton cloth",
        "sits",
        "1200 stuk",
        6000,
        "Coromandel",
        "Amsterdam",
        "1720-04-08",
        120000,
        "Massive chintz order for European re-export",
    ),
    (
        102,
        "das:4891",
        "silk",
        "zijde",
        "130 balen",
        3900,
        "Bengal",
        "Amsterdam",
        "1723-03-15",
        130000,
        "Premium Kasimbazar silk",
    ),
    (
        103,
        "das:4969",
        "cotton cloth",
        "katoen",
        "500 stuk",
        2500,
        "Surat",
        "Amsterdam",
        "1726-05-22",
        50000,
        "Surat cotton piece goods",
    ),
    (
        104,
        "das:5047",
        "silk",
        "zijde",
        "90 balen",
        2700,
        "Bengal",
        "Amsterdam",
        "1730-04-10",
        90000,
        "Bengal silk via Hooghly factory",
    ),
    (
        105,
        "das:5125",
        "cotton cloth",
        "sits",
        "850 stuk",
        4250,
        "Coromandel",
        "Amsterdam",
        "1733-02-18",
        85000,
        "Coromandel painted textiles, high demand",
    ),
    (
        106,
        "das:5203",
        "silk",
        "zijde",
        "110 balen",
        3300,
        "Bengal",
        "Amsterdam",
        "1736-03-28",
        110000,
        "Fine Murshidabad silk",
    ),
    (
        107,
        "das:5281",
        "cotton cloth",
        "katoen",
        "650 stuk",
        3250,
        "Masulipatnam",
        "Amsterdam",
        "1739-05-12",
        65000,
        "Masulipatnam cotton, moderate quality",
    ),
    (
        108,
        "das:5359",
        "silk",
        "zijde",
        "70 balen",
        2100,
        "Bengal",
        "Amsterdam",
        "1742-04-08",
        70000,
        "Reduced silk trade due to Bengal unrest",
    ),
    (
        109,
        "das:5437",
        "cotton cloth",
        "sits",
        "950 stuk",
        4750,
        "Coromandel",
        "Amsterdam",
        "1745-02-20",
        95000,
        "Chintz for Dutch domestic market",
    ),
    (
        110,
        "das:5515",
        "silk",
        "zijde",
        "85 balen",
        2550,
        "Bengal",
        "Amsterdam",
        "1750-03-15",
        85000,
        "Bengal silk, competition from Chinese silk",
    ),
    (
        111,
        "das:5593",
        "cotton cloth",
        "katoen",
        "400 stuk",
        2000,
        "Surat",
        "Amsterdam",
        "1755-05-22",
        40000,
        "Surat calico, declining VOC textile trade",
    ),
    (
        112,
        "das:5671",
        "silk",
        "zijde",
        "50 balen",
        1500,
        "Bengal",
        "Amsterdam",
        "1760-04-10",
        50000,
        "Small silk shipment, Bengal turmoil",
    ),
    (
        113,
        "das:5749",
        "cotton cloth",
        "sits",
        "550 stuk",
        2750,
        "Coromandel",
        "Amsterdam",
        "1768-02-28",
        55000,
        "Coromandel chintz, reduced demand",
    ),
    (
        114,
        "das:5827",
        "silk",
        "zijde",
        "40 balen",
        1200,
        "Bengal",
        "Amsterdam",
        "1775-03-18",
        40000,
        "Bengal silk trade nearly ended",
    ),
    (
        115,
        "das:5905",
        "cotton cloth",
        "katoen",
        "300 stuk",
        1500,
        "Coromandel",
        "Amsterdam",
        "1785-05-12",
        30000,
        "Late VOC textile shipment, minimal volume",
    ),
    # -----------------------------------------------------------------------
    # PORCELAIN (~15 records) -- Chinese ceramics
    # -----------------------------------------------------------------------
    (
        116,
        "das:4067",
        "porcelain",
        "porselein",
        "200 kisten",
        10000,
        "Canton",
        "Amsterdam",
        "1701-05-22",
        60000,
        "Blue-and-white Chinese export porcelain",
    ),
    (
        117,
        "das:4167",
        "porcelain",
        "porselein",
        "350 kisten",
        17500,
        "Canton",
        "Amsterdam",
        "1706-04-14",
        105000,
        "Large porcelain order, famille verte patterns",
    ),
    (
        118,
        "das:4278",
        "porcelain",
        "porselein",
        "150 kisten",
        7500,
        "Canton",
        "Amsterdam",
        "1710-03-28",
        45000,
        "Kangxi period blue-and-white porcelain",
    ),
    (
        119,
        "das:4389",
        "porcelain",
        "porselein",
        "280 kisten",
        14000,
        "Canton",
        "Amsterdam",
        "1715-05-18",
        84000,
        "Mixed porcelain cargo, plates and bowls",
    ),
    (
        120,
        "das:4478",
        "porcelain",
        "porselein",
        "500 kisten",
        25000,
        "Canton",
        "Amsterdam",
        "1720-02-10",
        150000,
        "Massive porcelain order for European nobility",
    ),
    (
        121,
        "das:4567",
        "porcelain",
        "porselein",
        "180 kisten",
        9000,
        "Canton",
        "Amsterdam",
        "1725-04-22",
        54000,
        "Yongzheng period porcelain, refined styles",
    ),
    (
        122,
        "das:4656",
        "porcelain",
        "porselein",
        "320 kisten",
        16000,
        "Canton",
        "Amsterdam",
        "1730-03-10",
        96000,
        "Armorial porcelain for Dutch families",
    ),
    (
        123,
        "das:4745",
        "porcelain",
        "porselein",
        "250 kisten",
        12500,
        "Canton",
        "Amsterdam",
        "1735-05-28",
        75000,
        "Famille rose porcelain, new fashion",
    ),
    (
        124,
        "das:4834",
        "porcelain",
        "porselein",
        "400 kisten",
        20000,
        "Canton",
        "Amsterdam",
        "1740-04-14",
        120000,
        "Qianlong porcelain, high-quality export ware",
    ),
    (
        125,
        "das:4923",
        "porcelain",
        "porselein",
        "130 kisten",
        6500,
        "Canton",
        "Amsterdam",
        "1748-02-20",
        39000,
        "Select porcelain for Amsterdam dealers",
    ),
    (
        126,
        "das:5012",
        "porcelain",
        "porselein",
        "220 kisten",
        11000,
        "Canton",
        "Amsterdam",
        "1755-03-15",
        66000,
        "Chinese porcelain, Qianlong period peak",
    ),
    (
        127,
        "das:5101",
        "porcelain",
        "porselein",
        "170 kisten",
        8500,
        "Canton",
        "Amsterdam",
        "1762-05-22",
        51000,
        "Export porcelain with European-inspired designs",
    ),
    (
        128,
        "das:5190",
        "porcelain",
        "porselein",
        "100 kisten",
        5000,
        "Canton",
        "Amsterdam",
        "1770-04-08",
        30000,
        "Declining porcelain trade, European factories competing",
    ),
    (
        129,
        "das:5279",
        "porcelain",
        "porselein",
        "80 kisten",
        4000,
        "Canton",
        "Amsterdam",
        "1780-02-28",
        24000,
        "Wartime porcelain shipment, Fourth Anglo-Dutch War",
    ),
    (
        130,
        "das:5368",
        "porcelain",
        "porselein",
        "50 kisten",
        2500,
        "Canton",
        "Amsterdam",
        "1792-03-18",
        15000,
        "Final years of VOC porcelain trade",
    ),
    # -----------------------------------------------------------------------
    # TEA (~15 records) -- Growing trade in 18th century
    # -----------------------------------------------------------------------
    (
        131,
        "das:4489",
        "tea",
        "thee",
        "120 kisten",
        3600,
        "Canton",
        "Amsterdam",
        "1720-04-22",
        48000,
        "Early Canton tea imports, bohea and green",
    ),
    (
        132,
        "das:4578",
        "tea",
        "thee",
        "200 kisten",
        6000,
        "Canton",
        "Amsterdam",
        "1725-03-10",
        80000,
        "Growing Dutch tea consumption, bohea tea",
    ),
    (
        133,
        "das:4667",
        "tea",
        "thee",
        "350 kisten",
        10500,
        "Canton",
        "Amsterdam",
        "1730-05-18",
        140000,
        "Expanding tea trade, multiple varieties",
    ),
    (
        134,
        "das:4756",
        "tea",
        "thee",
        "280 kisten",
        8400,
        "Canton",
        "Amsterdam",
        "1734-04-08",
        112000,
        "Bohea and hyson tea for Dutch market",
    ),
    (
        135,
        "das:4845",
        "tea",
        "thee",
        "450 kisten",
        13500,
        "Canton",
        "Amsterdam",
        "1738-02-20",
        180000,
        "Major tea shipment, tea becoming staple beverage",
    ),
    (
        136,
        "das:4934",
        "tea",
        "thee",
        "380 kisten",
        11400,
        "Canton",
        "Amsterdam",
        "1742-03-15",
        152000,
        "Assorted teas for Amsterdam tea auction",
    ),
    (
        137,
        "das:5023",
        "tea",
        "thee",
        "500 kisten",
        15000,
        "Canton",
        "Amsterdam",
        "1746-05-22",
        200000,
        "Peak VOC tea trade, bohea dominant",
    ),
    (
        138,
        "das:5112",
        "tea",
        "thee",
        "420 kisten",
        12600,
        "Canton",
        "Amsterdam",
        "1750-04-10",
        168000,
        "Large tea cargo, competitive with EIC imports",
    ),
    (
        139,
        "das:5201",
        "tea",
        "thee",
        "550 kisten",
        16500,
        "Canton",
        "Amsterdam",
        "1754-02-28",
        220000,
        "Record tea shipment for VOC Canton factory",
    ),
    (
        140,
        "das:5290",
        "tea",
        "thee",
        "480 kisten",
        14400,
        "Canton",
        "Amsterdam",
        "1758-03-18",
        192000,
        "Green and black teas for Dutch re-export",
    ),
    (
        141,
        "das:5379",
        "tea",
        "thee",
        "600 kisten",
        18000,
        "Canton",
        "Amsterdam",
        "1762-05-12",
        240000,
        "Largest VOC tea cargo, peak of Canton trade",
    ),
    (
        142,
        "das:5468",
        "tea",
        "thee",
        "350 kisten",
        10500,
        "Canton",
        "Amsterdam",
        "1770-04-08",
        140000,
        "Tea trade declining relative to competitors",
    ),
    (
        143,
        "das:5557",
        "tea",
        "thee",
        "400 kisten",
        12000,
        "Canton",
        "Amsterdam",
        "1778-02-20",
        160000,
        "Wartime tea shipment under escort",
    ),
    (
        144,
        "das:5646",
        "tea",
        "thee",
        "250 kisten",
        7500,
        "Canton",
        "Amsterdam",
        "1785-03-15",
        100000,
        "Reduced tea trade, British dominance in Canton",
    ),
    (
        145,
        "das:5735",
        "tea",
        "thee",
        "180 kisten",
        5400,
        "Canton",
        "Amsterdam",
        "1793-05-22",
        72000,
        "Late VOC tea cargo, company near bankruptcy",
    ),
    # -----------------------------------------------------------------------
    # COFFEE (~10 records) -- Java coffee, growing importance from 1720s
    # -----------------------------------------------------------------------
    (
        146,
        "das:4501",
        "coffee",
        "koffie",
        "200 balen",
        12000,
        "Batavia",
        "Amsterdam",
        "1722-03-28",
        40000,
        "First major Java coffee shipments begin",
    ),
    (
        147,
        "das:4590",
        "coffee",
        "koffie",
        "350 balen",
        21000,
        "Batavia",
        "Amsterdam",
        "1726-05-12",
        70000,
        "Java coffee rapidly gaining popularity",
    ),
    (
        148,
        "das:4679",
        "coffee",
        "koffie",
        "500 balen",
        30000,
        "Batavia",
        "Amsterdam",
        "1730-04-08",
        100000,
        "Large Java coffee consignment, forced cultivation",
    ),
    (
        149,
        "das:4768",
        "coffee",
        "koffie",
        "450 balen",
        27000,
        "Batavia",
        "Amsterdam",
        "1735-02-20",
        90000,
        "Priangan highlands coffee, excellent flavour",
    ),
    (
        150,
        "das:4857",
        "coffee",
        "koffie",
        "600 balen",
        36000,
        "Batavia",
        "Amsterdam",
        "1740-03-15",
        120000,
        "Peak Java coffee production under preanger stelsel",
    ),
    (
        151,
        "das:4946",
        "coffee",
        "koffie",
        "550 balen",
        33000,
        "Batavia",
        "Amsterdam",
        "1745-05-22",
        110000,
        "Java coffee dominant in European market",
    ),
    (
        152,
        "das:5035",
        "coffee",
        "koffie",
        "700 balen",
        42000,
        "Batavia",
        "Amsterdam",
        "1750-04-10",
        140000,
        "Massive coffee cargo, coffee houses flourishing",
    ),
    (
        153,
        "das:5124",
        "coffee",
        "koffie",
        "480 balen",
        28800,
        "Batavia",
        "Amsterdam",
        "1760-02-28",
        96000,
        "Continued Java coffee exports despite VOC troubles",
    ),
    (
        154,
        "das:5213",
        "coffee",
        "koffie",
        "400 balen",
        24000,
        "Batavia",
        "Amsterdam",
        "1775-03-18",
        80000,
        "Java coffee, competition from Caribbean plantations",
    ),
    (
        155,
        "das:5302",
        "coffee",
        "koffie",
        "300 balen",
        18000,
        "Batavia",
        "Amsterdam",
        "1790-05-12",
        60000,
        "Late VOC Java coffee, reduced forced deliveries",
    ),
    # -----------------------------------------------------------------------
    # SILVER (~15 records) -- OUTBOUND cargo to Asia
    # -----------------------------------------------------------------------
    (
        156,
        "das:4078",
        "silver",
        "zilver",
        "50 kisten",
        15000,
        "Amsterdam",
        "Batavia",
        "1700-10-15",
        250000,
        "Silver specie for Batavia treasury and Asian purchases",
    ),
    (
        157,
        "das:4167",
        "silver",
        "zilver",
        "80 kisten",
        24000,
        "Amsterdam",
        "Batavia",
        "1704-11-22",
        400000,
        "Major silver shipment, Spanish reales and Dutch rijksdaalders",
    ),
    (
        158,
        "das:4256",
        "silver",
        "zilver",
        "60 kisten",
        18000,
        "Amsterdam",
        "Batavia",
        "1708-10-10",
        300000,
        "Outbound silver for intra-Asian trade finance",
    ),
    (
        159,
        "das:4345",
        "silver",
        "zilver",
        "100 kisten",
        30000,
        "Amsterdam",
        "Batavia",
        "1712-11-18",
        500000,
        "Largest silver shipment of the decade",
    ),
    (
        160,
        "das:4434",
        "silver",
        "zilver",
        "70 kisten",
        21000,
        "Amsterdam",
        "Batavia",
        "1716-10-28",
        350000,
        "Silver bars and coin for Asian commerce",
    ),
    (
        161,
        "das:4523",
        "silver",
        "zilver",
        "90 kisten",
        27000,
        "Amsterdam",
        "Batavia",
        "1720-11-08",
        450000,
        "Heavy silver cargo, critical for spice purchases",
    ),
    (
        162,
        "das:4612",
        "silver",
        "zilver",
        "55 kisten",
        16500,
        "Amsterdam",
        "Batavia",
        "1725-10-15",
        275000,
        "Spanish American silver via Amsterdam exchange",
    ),
    (
        163,
        "das:4701",
        "silver",
        "zilver",
        "75 kisten",
        22500,
        "Amsterdam",
        "Batavia",
        "1730-11-22",
        375000,
        "Silver for Ceylon, Coromandel, and Batavia",
    ),
    (
        164,
        "das:4790",
        "silver",
        "zilver",
        "85 kisten",
        25500,
        "Amsterdam",
        "Batavia",
        "1735-10-10",
        425000,
        "Annual silver remittance to Asian factories",
    ),
    (
        165,
        "das:4879",
        "silver",
        "zilver",
        "65 kisten",
        19500,
        "Amsterdam",
        "Batavia",
        "1740-11-18",
        325000,
        "Wartime silver shipment, Austrian Succession",
    ),
    (
        166,
        "das:4968",
        "silver",
        "zilver",
        "95 kisten",
        28500,
        "Amsterdam",
        "Batavia",
        "1745-10-28",
        475000,
        "Post-war silver replenishment for Asian trade",
    ),
    (
        167,
        "das:5057",
        "silver",
        "zilver",
        "45 kisten",
        13500,
        "Amsterdam",
        "Batavia",
        "1752-11-08",
        225000,
        "Reduced silver shipment, Company debts mounting",
    ),
    (
        168,
        "das:5146",
        "silver",
        "zilver",
        "50 kisten",
        15000,
        "Amsterdam",
        "Batavia",
        "1762-10-15",
        250000,
        "Silver for Canton tea purchases via Batavia",
    ),
    (
        169,
        "das:5235",
        "silver",
        "zilver",
        "35 kisten",
        10500,
        "Amsterdam",
        "Batavia",
        "1775-11-22",
        175000,
        "Declining silver exports, VOC liquidity crisis",
    ),
    (
        170,
        "das:5324",
        "silver",
        "zilver",
        "25 kisten",
        7500,
        "Amsterdam",
        "Batavia",
        "1788-10-10",
        125000,
        "Minimal silver shipment, VOC near insolvency",
    ),
    # -----------------------------------------------------------------------
    # OTHER COMMODITIES (~30 records)
    # -----------------------------------------------------------------------
    # Indigo
    (
        171,
        "das:4090",
        "indigo",
        "indigo",
        "80 kisten",
        4800,
        "Bengal",
        "Amsterdam",
        "1701-04-14",
        32000,
        "Bengal indigo dye, deep blue quality",
    ),
    (
        172,
        "das:4289",
        "indigo",
        "indigo",
        "120 kisten",
        7200,
        "Bengal",
        "Amsterdam",
        "1710-05-22",
        48000,
        "Premium Bengal indigo for textile dyeing",
    ),
    (
        173,
        "das:4501",
        "indigo",
        "indigo",
        "100 kisten",
        6000,
        "Batavia",
        "Amsterdam",
        "1720-03-18",
        40000,
        "Java-grown indigo, substitute for Bengal product",
    ),
    (
        174,
        "das:4712",
        "indigo",
        "indigo",
        "150 kisten",
        9000,
        "Bengal",
        "Amsterdam",
        "1730-04-28",
        60000,
        "Large indigo consignment for Amsterdam dye market",
    ),
    (
        175,
        "das:4923",
        "indigo",
        "indigo",
        "90 kisten",
        5400,
        "Batavia",
        "Amsterdam",
        "1742-05-10",
        36000,
        "Java indigo, fair quality",
    ),
    # Tin
    (
        176,
        "das:4101",
        "tin",
        "tin",
        "300 picul",
        18000,
        "Malacca",
        "Amsterdam",
        "1703-03-22",
        36000,
        "Bangka tin, VOC monopoly from Palembang",
    ),
    (
        177,
        "das:4312",
        "tin",
        "tin",
        "250 picul",
        15000,
        "Malacca",
        "Amsterdam",
        "1712-04-10",
        30000,
        "Straits tin from Bangka Island",
    ),
    (
        178,
        "das:4523",
        "tin",
        "tin",
        "400 picul",
        24000,
        "Malacca",
        "Amsterdam",
        "1722-05-18",
        48000,
        "Large Bangka tin shipment for European metalworkers",
    ),
    (
        179,
        "das:4734",
        "tin",
        "tin",
        "350 picul",
        21000,
        "Malacca",
        "Amsterdam",
        "1732-02-28",
        42000,
        "Bangka tin, smelted into ingots",
    ),
    (
        180,
        "das:4945",
        "tin",
        "tin",
        "200 picul",
        12000,
        "Malacca",
        "Amsterdam",
        "1745-03-15",
        24000,
        "Reduced tin production at Bangka mines",
    ),
    # Copper
    (
        181,
        "das:4134",
        "copper",
        "koper",
        "180 picul",
        10800,
        "Deshima",
        "Amsterdam",
        "1704-04-28",
        36000,
        "Japanese copper from Nagasaki via Deshima factory",
    ),
    (
        182,
        "das:4345",
        "copper",
        "koper",
        "250 picul",
        15000,
        "Deshima",
        "Amsterdam",
        "1714-03-10",
        50000,
        "Deshima copper bars, high purity",
    ),
    (
        183,
        "das:4556",
        "copper",
        "koper",
        "200 picul",
        12000,
        "Deshima",
        "Amsterdam",
        "1724-05-22",
        40000,
        "Japanese copper for Dutch minting and trade",
    ),
    (
        184,
        "das:4767",
        "copper",
        "koper",
        "150 picul",
        9000,
        "Deshima",
        "Amsterdam",
        "1734-04-08",
        30000,
        "Declining Japanese copper exports under Tokugawa restrictions",
    ),
    # Camphor
    (
        185,
        "das:4178",
        "camphor",
        "kamfer",
        "40 picul",
        2400,
        "Borneo",
        "Amsterdam",
        "1706-05-18",
        16000,
        "Borneo camphor, prized for medicinal use",
    ),
    (
        186,
        "das:4489",
        "camphor",
        "kamfer",
        "60 picul",
        3600,
        "Sumatra",
        "Amsterdam",
        "1718-04-14",
        24000,
        "Baros camphor from Sumatran west coast",
    ),
    # Sandalwood
    (
        187,
        "das:4223",
        "sandalwood",
        "sandelhout",
        "100 picul",
        6000,
        "Timor",
        "Amsterdam",
        "1708-03-28",
        20000,
        "Timor sandalwood, fragrant heartwood",
    ),
    (
        188,
        "das:4534",
        "sandalwood",
        "sandelhout",
        "80 picul",
        4800,
        "Timor",
        "Amsterdam",
        "1720-05-10",
        16000,
        "Sandalwood for incense and furniture making",
    ),
    # Saltpeter
    (
        189,
        "das:4267",
        "saltpeter",
        "salpeter",
        "200 picul",
        12000,
        "Bengal",
        "Amsterdam",
        "1709-04-22",
        20000,
        "Bengal saltpeter for Dutch gunpowder production",
    ),
    (
        190,
        "das:4578",
        "saltpeter",
        "salpeter",
        "300 picul",
        18000,
        "Bengal",
        "Amsterdam",
        "1722-03-10",
        30000,
        "Large saltpeter consignment for military supply",
    ),
    (
        191,
        "das:4890",
        "saltpeter",
        "salpeter",
        "250 picul",
        15000,
        "Bengal",
        "Amsterdam",
        "1735-05-28",
        25000,
        "Bengal saltpeter via Hooghly factory",
    ),
    # Opium
    (
        192,
        "das:4301",
        "opium",
        "opium",
        "50 kisten",
        1500,
        "Bengal",
        "Batavia",
        "1710-04-18",
        25000,
        "Bengal opium for intra-Asian trade, sold in Java",
    ),
    (
        193,
        "das:4612",
        "opium",
        "opium",
        "80 kisten",
        2400,
        "Bengal",
        "Batavia",
        "1725-03-22",
        40000,
        "Patna opium, VOC monopoly in East Indies market",
    ),
    (
        194,
        "das:4923",
        "opium",
        "opium",
        "120 kisten",
        3600,
        "Bengal",
        "Batavia",
        "1740-05-14",
        60000,
        "Growing opium consumption in Java and Malay states",
    ),
    # Sugar
    (
        195,
        "das:4356",
        "sugar",
        "suiker",
        "500 picul",
        30000,
        "Batavia",
        "Amsterdam",
        "1712-02-18",
        25000,
        "Java sugar from Chinese-run mills near Batavia",
    ),
    (
        196,
        "das:4667",
        "sugar",
        "suiker",
        "800 picul",
        48000,
        "Batavia",
        "Amsterdam",
        "1726-04-28",
        40000,
        "Expanding Java sugar production for Dutch market",
    ),
    (
        197,
        "das:4978",
        "sugar",
        "suiker",
        "600 picul",
        36000,
        "Batavia",
        "Amsterdam",
        "1738-03-10",
        30000,
        "Java sugar, competing with Caribbean imports",
    ),
    # Rice
    (
        198,
        "das:4412",
        "rice",
        "rijst",
        "1000 picul",
        60000,
        "Batavia",
        "Ceylon",
        "1715-02-28",
        5000,
        "Java rice for Ceylon garrison provisioning",
    ),
    (
        199,
        "das:4723",
        "rice",
        "rijst",
        "1500 picul",
        90000,
        "Bengal",
        "Batavia",
        "1730-04-14",
        7500,
        "Bengal rice for Batavia warehouses and ships",
    ),
    # Diamonds
    (
        200,
        "das:4501",
        "diamonds",
        "diamanten",
        "1 kistje",
        2,
        "Coromandel",
        "Amsterdam",
        "1720-05-28",
        350000,
        "Golconda diamonds, sealed casket for Heren XVII",
    ),
]


def build_cargo() -> list[dict]:
    """Return ~200 curated VOC cargo manifest records."""
    records = []
    for row in CARGO_RAW:
        (
            num,
            voyage_id,
            commodity,
            commodity_dutch,
            quantity,
            quantity_kg,
            origin,
            destination,
            date,
            value_guilders,
            notes,
        ) = row
        records.append(
            {
                "cargo_id": f"voc_cargo:{num:06d}",
                "voyage_id": voyage_id,
                "commodity": commodity,
                "commodity_dutch": commodity_dutch,
                "quantity": quantity,
                "quantity_kg": quantity_kg,
                "origin": origin,
                "destination": destination,
                "date": date,
                "value_guilders": value_guilders,
                "notes": notes,
            }
        )
    return records


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    args = parse_args("Generate VOC cargo manifest data")

    print("=" * 60)
    print("VOC Cargo Data Generation -- chuk-mcp-maritime-archives")
    print("=" * 60)
    print(f"\nData directory: {DATA_DIR}\n")

    if not args.force and is_cached(OUTPUT, args.cache_max_age):
        print(f"Using cached {OUTPUT.name} (use --force to regenerate)")
        return

    DATA_DIR.mkdir(parents=True, exist_ok=True)

    # -- Generate cargo records --
    print("Generating VOC cargo manifest records ...")
    cargo = build_cargo()
    with open(OUTPUT, "w") as f:
        json.dump(cargo, f, indent=2, ensure_ascii=False)
    print(f"  {OUTPUT}")
    print(f"  {len(cargo)} records written ({OUTPUT.stat().st_size:,} bytes)")

    # -- Validate cargo_id uniqueness and sequential numbering --
    print("\nValidation:")
    expected_ids = {f"voc_cargo:{i:06d}" for i in range(1, len(cargo) + 1)}
    actual_ids = {c["cargo_id"] for c in cargo}
    assert expected_ids == actual_ids, (
        f"cargo_id mismatch.\n"
        f"  Missing: {expected_ids - actual_ids}\n"
        f"  Extra:   {actual_ids - expected_ids}"
    )
    print(f"  cargo_id uniqueness: OK ({len(actual_ids)} unique IDs, sequential 1-{len(cargo)})")

    # -- Validate all required fields present --
    required_fields = [
        "cargo_id",
        "voyage_id",
        "commodity",
        "commodity_dutch",
        "quantity",
        "quantity_kg",
        "origin",
        "destination",
        "date",
        "value_guilders",
        "notes",
    ]
    for i, rec in enumerate(cargo):
        for field in required_fields:
            assert field in rec, f"Record {i + 1} missing field: {field}"
    print(f"  Required fields: OK (all {len(required_fields)} fields present in every record)")

    # -- Print summary: commodity distribution --
    commodity_counts: dict[str, int] = {}
    commodity_values: dict[str, int] = {}
    for rec in cargo:
        c = rec["commodity"]
        commodity_counts[c] = commodity_counts.get(c, 0) + 1
        commodity_values[c] = commodity_values.get(c, 0) + rec["value_guilders"]

    print(f"\n  Commodity distribution ({len(commodity_counts)} categories):")
    for c in sorted(commodity_counts, key=lambda x: commodity_counts[x], reverse=True):
        print(f"    {c:20s}  {commodity_counts[c]:3d} records  {commodity_values[c]:>12,} guilders")

    # -- Total value --
    total_value = sum(rec["value_guilders"] for rec in cargo)
    print(f"\n  Total cargo value: {total_value:,} guilders")

    # -- Date range --
    dates = sorted(rec["date"] for rec in cargo)
    print(f"  Date range: {dates[0]} to {dates[-1]}")

    # -- Decade distribution --
    decade_counts: dict[str, int] = {}
    for rec in cargo:
        decade = rec["date"][:3] + "0s"
        decade_counts[decade] = decade_counts.get(decade, 0) + 1
    print("\n  Decade distribution:")
    for decade in sorted(decade_counts):
        print(f"    {decade}: {decade_counts[decade]:3d} records")

    print(f"\n{'=' * 60}")
    print("VOC cargo data generation complete!")
    print(f"  Records: {len(cargo)}")
    print(f"  Output:  {OUTPUT}")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()
