#!/usr/bin/env python3
"""
Generate curated UK Hydrographic Office wreck data (fallback subset).

Produces ~50 representative wrecks spanning the 16th-20th centuries,
drawn from well-documented shipwrecks worldwide.  This curated dataset
ships with the repo and serves as a fallback when the full 94K-record
UKHO dataset has not been downloaded via download_ukho.py.

Source data compiled from:
    UK Hydrographic Office. Database of Wrecks and Obstructions.
    Open Government Licence v3.0.

Produces:
    data/ukho_wrecks.json  -- ~50 wreck records (ukho_wreck:00001 .. 00050)

Usage:
    python scripts/generate_ukho.py
    python scripts/generate_ukho.py --force
"""

from download_utils import DATA_DIR, is_cached, parse_args, save_json

WRECKS_OUTPUT = DATA_DIR / "ukho_wrecks.json"
ARCHIVE = "ukho"

# ---------------------------------------------------------------------------
# Curated wreck data
# ---------------------------------------------------------------------------

WRECKS_RAW = [
    # --- UK flagged ---
    {
        "n": 1,
        "ship": "Mary Rose",
        "date": "1545-07-19",
        "cause": "battle",
        "location": "The Solent, off Portsmouth",
        "region": "english_channel",
        "status": "found",
        "lat": 50.76,
        "lon": -1.11,
        "unc": 0.01,
        "depth": 12,
        "flag": "UK",
        "type": "carrack",
    },
    {
        "n": 2,
        "ship": "HMS Association",
        "date": "1707-10-22",
        "cause": "reef",
        "location": "Isles of Scilly",
        "region": "english_channel",
        "status": "found",
        "lat": 49.88,
        "lon": -6.38,
        "unc": 0.1,
        "depth": 20,
        "flag": "UK",
        "type": "warship",
    },
    {
        "n": 3,
        "ship": "HMS Birkenhead",
        "date": "1852-02-26",
        "cause": "reef",
        "location": "Danger Point, near Gansbaai",
        "region": "cape",
        "status": "found",
        "lat": -34.63,
        "lon": 19.30,
        "unc": 0.5,
        "depth": 30,
        "flag": "UK",
        "type": "troopship",
    },
    {
        "n": 4,
        "ship": "SS Mendi",
        "date": "1917-02-21",
        "cause": "collision",
        "location": "English Channel, off Isle of Wight",
        "region": "english_channel",
        "status": "found",
        "lat": 50.47,
        "lon": -1.28,
        "unc": 0.1,
        "depth": 15,
        "flag": "UK",
        "type": "transport",
    },
    {
        "n": 5,
        "ship": "RMS Lusitania",
        "date": "1915-05-07",
        "cause": "battle",
        "location": "Off Old Head of Kinsale, Ireland",
        "region": "atlantic_europe",
        "status": "found",
        "lat": 51.73,
        "lon": -8.55,
        "unc": 0.1,
        "depth": 93,
        "flag": "UK",
        "type": "liner",
    },
    {
        "n": 6,
        "ship": "RMS Titanic",
        "date": "1912-04-15",
        "cause": "collision",
        "location": "North Atlantic, south of Newfoundland",
        "region": "north_atlantic",
        "status": "found",
        "lat": 41.73,
        "lon": -49.95,
        "unc": 0.01,
        "depth": 3800,
        "flag": "UK",
        "type": "liner",
    },
    {
        "n": 7,
        "ship": "HMS Victory (1744)",
        "date": "1744-10-05",
        "cause": "storm",
        "location": "English Channel, Casquets",
        "region": "english_channel",
        "status": "found",
        "lat": 49.72,
        "lon": -2.00,
        "unc": 5.0,
        "depth": 75,
        "flag": "UK",
        "type": "warship",
    },
    {
        "n": 8,
        "ship": "HMS Coventry",
        "date": "1982-05-25",
        "cause": "battle",
        "location": "North of Pebble Island, Falklands",
        "region": "south_atlantic",
        "status": "found",
        "lat": -51.05,
        "lon": -59.80,
        "unc": 0.1,
        "depth": 100,
        "flag": "UK",
        "type": "destroyer",
    },
    {
        "n": 9,
        "ship": "Earl of Abergavenny",
        "date": "1805-02-05",
        "cause": "grounding",
        "location": "Shambles Bank, off Weymouth",
        "region": "english_channel",
        "status": "found",
        "lat": 50.54,
        "lon": -2.39,
        "unc": 0.1,
        "depth": 12,
        "flag": "UK",
        "type": "east indiaman",
    },
    {
        "n": 10,
        "ship": "SS Treveal",
        "date": "1920-10-20",
        "cause": "storm",
        "location": "Gurnards Head, Cornwall",
        "region": "english_channel",
        "status": "found",
        "lat": 50.19,
        "lon": -5.60,
        "unc": 0.5,
        "depth": 18,
        "flag": "UK",
        "type": "cargo",
    },
    # --- Dutch flagged (VOC-era) ---
    {
        "n": 11,
        "ship": "Batavia",
        "date": "1629-06-04",
        "cause": "reef",
        "location": "Morning Reef, Houtman Abrolhos",
        "region": "australia_nz",
        "status": "found",
        "lat": -28.49,
        "lon": 113.79,
        "unc": 0.1,
        "depth": 5,
        "flag": "NL",
        "type": "retourschip",
    },
    {
        "n": 12,
        "ship": "Vergulde Draeck",
        "date": "1656-04-28",
        "cause": "reef",
        "location": "Ledge Point, Western Australia",
        "region": "australia_nz",
        "status": "found",
        "lat": -31.11,
        "lon": 115.33,
        "unc": 0.1,
        "depth": 7,
        "flag": "NL",
        "type": "retourschip",
    },
    {
        "n": 13,
        "ship": "Zuytdorp",
        "date": "1712-06-01",
        "cause": "reef",
        "location": "Zuytdorp Cliffs, Western Australia",
        "region": "australia_nz",
        "status": "found",
        "lat": -27.17,
        "lon": 113.98,
        "unc": 0.5,
        "depth": 3,
        "flag": "NL",
        "type": "retourschip",
    },
    {
        "n": 14,
        "ship": "Amsterdam",
        "date": "1749-01-26",
        "cause": "storm",
        "location": "Bulverhythe, near Hastings",
        "region": "english_channel",
        "status": "found",
        "lat": 50.85,
        "lon": 0.52,
        "unc": 0.01,
        "depth": 0,
        "flag": "NL",
        "type": "retourschip",
    },
    {
        "n": 15,
        "ship": "Rooswijk",
        "date": "1740-01-09",
        "cause": "reef",
        "location": "Goodwin Sands, Kent",
        "region": "english_channel",
        "status": "found",
        "lat": 51.24,
        "lon": 1.55,
        "unc": 0.1,
        "depth": 8,
        "flag": "NL",
        "type": "retourschip",
    },
    # --- Spanish flagged ---
    {
        "n": 16,
        "ship": "San Diego",
        "date": "1600-12-14",
        "cause": "battle",
        "location": "Fortune Island, Philippines",
        "region": "south_china_sea",
        "status": "found",
        "lat": 13.86,
        "lon": 121.22,
        "unc": 1.0,
        "depth": 52,
        "flag": "ES",
        "type": "galleon",
    },
    {
        "n": 17,
        "ship": "Nuestra Senora de Atocha",
        "date": "1622-09-06",
        "cause": "storm",
        "location": "Florida Keys",
        "region": "caribbean",
        "status": "found",
        "lat": 24.52,
        "lon": -82.20,
        "unc": 0.1,
        "depth": 16,
        "flag": "ES",
        "type": "galleon",
    },
    {
        "n": 18,
        "ship": "San Martin",
        "date": "1618-07-15",
        "cause": "storm",
        "location": "Saipan, Mariana Islands",
        "region": "pacific",
        "status": "unfound",
        "lat": 15.20,
        "lon": 145.75,
        "unc": 50.0,
        "depth": None,
        "flag": "ES",
        "type": "galleon",
    },
    {
        "n": 19,
        "ship": "Santa Maria de la Rosa",
        "date": "1588-09-21",
        "cause": "storm",
        "location": "Blasket Sound, Ireland",
        "region": "atlantic_europe",
        "status": "found",
        "lat": 52.07,
        "lon": -10.51,
        "unc": 0.5,
        "depth": 40,
        "flag": "ES",
        "type": "galleon",
    },
    {
        "n": 20,
        "ship": "Juncal",
        "date": "1631-10-28",
        "cause": "storm",
        "location": "Campeche Bank, Gulf of Mexico",
        "region": "caribbean",
        "status": "unfound",
        "lat": 21.50,
        "lon": -90.50,
        "unc": 100.0,
        "depth": None,
        "flag": "ES",
        "type": "galleon",
    },
    # --- Portuguese flagged ---
    {
        "n": 21,
        "ship": "Sao Joao",
        "date": "1552-06-24",
        "cause": "storm",
        "location": "Natal coast, South Africa",
        "region": "cape",
        "status": "found",
        "lat": -31.10,
        "lon": 30.30,
        "unc": 5.0,
        "depth": 10,
        "flag": "PT",
        "type": "carrack",
    },
    {
        "n": 22,
        "ship": "Sao Bento",
        "date": "1554-04-22",
        "cause": "storm",
        "location": "Msikaba River mouth, Pondoland",
        "region": "cape",
        "status": "found",
        "lat": -31.29,
        "lon": 29.96,
        "unc": 2.0,
        "depth": 8,
        "flag": "PT",
        "type": "carrack",
    },
    {
        "n": 23,
        "ship": "Sacramento",
        "date": "1647-06-30",
        "cause": "reef",
        "location": "Recife de Fora, Salvador, Brazil",
        "region": "south_atlantic",
        "status": "found",
        "lat": -12.98,
        "lon": -38.51,
        "unc": 0.1,
        "depth": 6,
        "flag": "PT",
        "type": "galleon",
    },
    {
        "n": 24,
        "ship": "Nossa Senhora da Luz",
        "date": "1615-03-12",
        "cause": "storm",
        "location": "Mozambique Channel",
        "region": "mozambique_channel",
        "status": "unfound",
        "lat": -15.50,
        "lon": 40.80,
        "unc": 50.0,
        "depth": None,
        "flag": "PT",
        "type": "carrack",
    },
    # --- Swedish flagged ---
    {
        "n": 25,
        "ship": "Vasa",
        "date": "1628-08-10",
        "cause": "grounding",
        "location": "Stockholm harbour",
        "region": "baltic",
        "status": "found",
        "lat": 59.33,
        "lon": 18.09,
        "unc": 0.01,
        "depth": 32,
        "flag": "SE",
        "type": "warship",
    },
    {
        "n": 26,
        "ship": "Kronan",
        "date": "1676-06-01",
        "cause": "battle",
        "location": "East of Oland, Baltic Sea",
        "region": "baltic",
        "status": "found",
        "lat": 56.60,
        "lon": 16.70,
        "unc": 0.1,
        "depth": 26,
        "flag": "SE",
        "type": "warship",
    },
    {
        "n": 27,
        "ship": "Gotheborg",
        "date": "1745-09-12",
        "cause": "grounding",
        "location": "Entrance to Gothenburg harbour",
        "region": "north_sea",
        "status": "found",
        "lat": 57.67,
        "lon": 11.78,
        "unc": 0.01,
        "depth": 8,
        "flag": "SE",
        "type": "east indiaman",
    },
    # --- German flagged ---
    {
        "n": 28,
        "ship": "SMS Scharnhorst",
        "date": "1914-12-08",
        "cause": "battle",
        "location": "Battle of the Falkland Islands",
        "region": "south_atlantic",
        "status": "found",
        "lat": -52.62,
        "lon": -56.25,
        "unc": 1.0,
        "depth": 1610,
        "flag": "DE",
        "type": "cruiser",
    },
    {
        "n": 29,
        "ship": "SMS Konig",
        "date": "1919-06-21",
        "cause": "scuttled",
        "location": "Scapa Flow, Orkney",
        "region": "north_sea",
        "status": "found",
        "lat": 58.88,
        "lon": -3.08,
        "unc": 0.01,
        "depth": 38,
        "flag": "DE",
        "type": "battleship",
    },
    # --- French flagged ---
    {
        "n": 30,
        "ship": "La Belle",
        "date": "1686-02-01",
        "cause": "storm",
        "location": "Matagorda Bay, Texas",
        "region": "caribbean",
        "status": "found",
        "lat": 28.58,
        "lon": -96.30,
        "unc": 0.01,
        "depth": 4,
        "flag": "FR",
        "type": "barque",
    },
    {
        "n": 31,
        "ship": "Meduse",
        "date": "1816-07-02",
        "cause": "grounding",
        "location": "Arguin Bank, Mauritania",
        "region": "west_africa",
        "status": "found",
        "lat": 19.87,
        "lon": -16.92,
        "unc": 5.0,
        "depth": 5,
        "flag": "FR",
        "type": "frigate",
    },
    # --- Italian ---
    {
        "n": 32,
        "ship": "SS Andrea Doria",
        "date": "1956-07-26",
        "cause": "collision",
        "location": "Nantucket, Massachusetts",
        "region": "north_atlantic",
        "status": "found",
        "lat": 40.30,
        "lon": -69.85,
        "unc": 0.01,
        "depth": 75,
        "flag": "IT",
        "type": "liner",
    },
    # --- Norwegian ---
    {
        "n": 33,
        "ship": "KNM Bluecher",
        "date": "1940-04-09",
        "cause": "battle",
        "location": "Drobak Narrows, Oslofjord",
        "region": "north_sea",
        "status": "found",
        "lat": 59.67,
        "lon": 10.60,
        "unc": 0.01,
        "depth": 64,
        "flag": "DE",
        "type": "cruiser",
    },
    # --- Japanese ---
    {
        "n": 34,
        "ship": "IJN Yamato",
        "date": "1945-04-07",
        "cause": "battle",
        "location": "East China Sea, south of Kyushu",
        "region": "japan",
        "status": "found",
        "lat": 30.43,
        "lon": 128.04,
        "unc": 0.5,
        "depth": 340,
        "flag": "JP",
        "type": "battleship",
    },
    # --- American ---
    {
        "n": 35,
        "ship": "USS Monitor",
        "date": "1862-12-31",
        "cause": "storm",
        "location": "Cape Hatteras, North Carolina",
        "region": "north_atlantic",
        "status": "found",
        "lat": 35.06,
        "lon": -75.94,
        "unc": 0.01,
        "depth": 73,
        "flag": "US",
        "type": "ironclad",
    },
    {
        "n": 36,
        "ship": "USS Arizona",
        "date": "1941-12-07",
        "cause": "battle",
        "location": "Pearl Harbor, Hawaii",
        "region": "north_pacific",
        "status": "found",
        "lat": 21.37,
        "lon": -157.95,
        "unc": 0.01,
        "depth": 12,
        "flag": "US",
        "type": "battleship",
    },
    {
        "n": 37,
        "ship": "SS Edmund Fitzgerald",
        "date": "1975-11-10",
        "cause": "storm",
        "location": "Lake Superior, Great Lakes",
        "region": "north_atlantic",
        "status": "found",
        "lat": 46.99,
        "lon": -85.11,
        "unc": 0.01,
        "depth": 160,
        "flag": "US",
        "type": "bulk carrier",
    },
    # --- Australian ---
    {
        "n": 38,
        "ship": "HMAS Sydney",
        "date": "1941-11-19",
        "cause": "battle",
        "location": "Off Shark Bay, Western Australia",
        "region": "australia_nz",
        "status": "found",
        "lat": -26.07,
        "lon": 111.07,
        "unc": 0.1,
        "depth": 2468,
        "flag": "AU",
        "type": "cruiser",
    },
    # --- Danish ---
    {
        "n": 39,
        "ship": "Prins Frederik",
        "date": "1890-01-18",
        "cause": "storm",
        "location": "Skagerrak, North Sea",
        "region": "north_sea",
        "status": "found",
        "lat": 57.85,
        "lon": 10.22,
        "unc": 2.0,
        "depth": 40,
        "flag": "DK",
        "type": "cargo",
    },
    # --- More wrecks for broad coverage ---
    {
        "n": 40,
        "ship": "SS Thistlegorm",
        "date": "1941-10-06",
        "cause": "battle",
        "location": "Red Sea, near Sharm el-Sheikh",
        "region": "arabian_sea",
        "status": "found",
        "lat": 27.81,
        "lon": 33.92,
        "unc": 0.01,
        "depth": 30,
        "flag": "UK",
        "type": "cargo",
    },
    {
        "n": 41,
        "ship": "Endurance",
        "date": "1915-11-21",
        "cause": "storm",
        "location": "Weddell Sea, Antarctica",
        "region": "south_atlantic",
        "status": "found",
        "lat": -68.80,
        "lon": -52.53,
        "unc": 0.01,
        "depth": 3008,
        "flag": "UK",
        "type": "barquentine",
    },
    {
        "n": 42,
        "ship": "SS Yongala",
        "date": "1911-03-23",
        "cause": "storm",
        "location": "Off Cape Bowling Green, Queensland",
        "region": "australia_nz",
        "status": "found",
        "lat": -19.30,
        "lon": 147.62,
        "unc": 0.01,
        "depth": 28,
        "flag": "AU",
        "type": "passenger",
    },
    {
        "n": 43,
        "ship": "Tek Sing",
        "date": "1822-02-06",
        "cause": "reef",
        "location": "Belvidere Shoal, South China Sea",
        "region": "south_china_sea",
        "status": "found",
        "lat": 2.00,
        "lon": 106.20,
        "unc": 1.0,
        "depth": 30,
        "flag": "CN",
        "type": "junk",
    },
    {
        "n": 44,
        "ship": "MV Dona Paz",
        "date": "1987-12-20",
        "cause": "collision",
        "location": "Tablas Strait, Philippines",
        "region": "south_china_sea",
        "status": "found",
        "lat": 12.50,
        "lon": 121.70,
        "unc": 1.0,
        "depth": 545,
        "flag": "PH",
        "type": "passenger",
    },
    {
        "n": 45,
        "ship": "SS Waratah",
        "date": "1909-07-27",
        "cause": "storm",
        "location": "Between Durban and Cape Town",
        "region": "cape",
        "status": "unfound",
        "lat": -32.00,
        "lon": 29.50,
        "unc": 200.0,
        "depth": None,
        "flag": "UK",
        "type": "liner",
    },
    {
        "n": 46,
        "ship": "MV Derbyshire",
        "date": "1980-09-09",
        "cause": "storm",
        "location": "South of Japan, Typhoon Orchid",
        "region": "north_pacific",
        "status": "found",
        "lat": 25.27,
        "lon": 133.10,
        "unc": 0.5,
        "depth": 4113,
        "flag": "UK",
        "type": "bulk carrier",
    },
    {
        "n": 47,
        "ship": "SS Central America",
        "date": "1857-09-12",
        "cause": "storm",
        "location": "Off Cape Hatteras, Atlantic",
        "region": "north_atlantic",
        "status": "found",
        "lat": 31.67,
        "lon": -77.00,
        "unc": 0.5,
        "depth": 2200,
        "flag": "US",
        "type": "steamer",
    },
    {
        "n": 48,
        "ship": "White Ship",
        "date": "1120-11-25",
        "cause": "reef",
        "location": "Barfleur, Normandy",
        "region": "english_channel",
        "status": "unfound",
        "lat": 49.67,
        "lon": -1.26,
        "unc": 10.0,
        "depth": None,
        "flag": "UK",
        "type": "longship",
    },
    {
        "n": 49,
        "ship": "MV Wilhelm Gustloff",
        "date": "1945-01-30",
        "cause": "battle",
        "location": "Baltic Sea, off Pomerania",
        "region": "baltic",
        "status": "found",
        "lat": 55.07,
        "lon": 17.42,
        "unc": 0.1,
        "depth": 44,
        "flag": "DE",
        "type": "transport",
    },
    {
        "n": 50,
        "ship": "RMS Empress of Ireland",
        "date": "1914-05-29",
        "cause": "collision",
        "location": "St Lawrence River, Quebec",
        "region": "north_atlantic",
        "status": "found",
        "lat": 48.63,
        "lon": -68.38,
        "unc": 0.01,
        "depth": 40,
        "flag": "CA",
        "type": "liner",
    },
]


def build_wrecks() -> list[dict]:
    """Convert raw wreck data to standard format."""
    wrecks = []
    for w in WRECKS_RAW:
        wreck_id = f"{ARCHIVE}_wreck:{w['n']:05d}"
        position = {
            "lat": w["lat"],
            "lon": w["lon"],
            "uncertainty_km": w["unc"],
        }
        rec = {
            "wreck_id": wreck_id,
            "ship_name": w["ship"],
            "loss_date": w["date"],
            "loss_cause": w["cause"],
            "loss_location": w["location"],
            "region": w["region"],
            "status": w["status"],
            "position": position,
            "depth_estimate_m": w["depth"],
            "flag": w["flag"],
            "vessel_type": w["type"],
            "archive": ARCHIVE,
        }
        wrecks.append(rec)
    return wrecks


def main() -> None:
    args = parse_args("Generate UKHO curated wreck data (fallback subset)")

    if not args.force and is_cached(WRECKS_OUTPUT, args.cache_max_age):
        print(f"  {WRECKS_OUTPUT.name} is up to date (use --force to regenerate)")
        return

    wrecks = build_wrecks()

    # Validate IDs
    expected_ids = {f"{ARCHIVE}_wreck:{i:05d}" for i in range(1, len(wrecks) + 1)}
    actual_ids = {w["wreck_id"] for w in wrecks}
    assert expected_ids == actual_ids, f"ID mismatch: {expected_ids - actual_ids}"

    for w in wrecks:
        assert w["archive"] == ARCHIVE

    save_json(wrecks, WRECKS_OUTPUT.name)
    print(f"  Generated {len(wrecks)} UKHO curated wrecks")


if __name__ == "__main__":
    main()
