#!/usr/bin/env python3
"""
Generate curated NOAA AWOIS wreck data (fallback subset).

Produces ~50 representative wrecks in US coastal waters, spanning
colonial era through the 20th century.  This curated dataset ships
with the repo and serves as a fallback when the full ~13K-record
NOAA dataset has not been downloaded via download_noaa.py.

Source data compiled from:
    NOAA Office of Coast Survey. Automated Wreck and Obstruction
    Information System (AWOIS). Public Domain (US Government).

Produces:
    data/noaa_wrecks.json  -- ~50 wreck records (noaa_wreck:00001 .. 00050)

Usage:
    python scripts/generate_noaa.py
    python scripts/generate_noaa.py --force
"""

from download_utils import DATA_DIR, is_cached, parse_args, save_json

WRECKS_OUTPUT = DATA_DIR / "noaa_wrecks.json"
ARCHIVE = "noaa"

# ---------------------------------------------------------------------------
# Curated wreck data — famous and representative US wrecks
# ---------------------------------------------------------------------------

WRECKS_RAW = [
    # --- Civil War era ---
    {
        "n": 1,
        "ship": "USS Monitor",
        "date": "1862-12-31",
        "cause": "storm",
        "location": "Cape Hatteras, North Carolina",
        "region": "north_atlantic",
        "status": "found",
        "lat": 35.06,
        "lon": -75.94,
        "unc": 0.03,
        "depth": 73,
        "flag": "US",
        "type": "ironclad",
        "gp": 1,
    },
    {
        "n": 2,
        "ship": "CSS Alabama",
        "date": "1864-06-19",
        "cause": "battle",
        "location": "Off Cherbourg, France (US-flagged raider)",
        "region": "north_atlantic",
        "status": "found",
        "lat": 49.84,
        "lon": -1.73,
        "unc": 0.1,
        "depth": 60,
        "flag": "US",
        "type": "warship",
        "gp": 1,
    },
    {
        "n": 3,
        "ship": "USS Housatonic",
        "date": "1864-02-17",
        "cause": "battle",
        "location": "Charleston Harbor, South Carolina",
        "region": "north_atlantic",
        "status": "found",
        "lat": 32.72,
        "lon": -79.78,
        "unc": 0.03,
        "depth": 9,
        "flag": "US",
        "type": "warship",
        "gp": 1,
    },
    {
        "n": 4,
        "ship": "CSS H.L. Hunley",
        "date": "1864-02-17",
        "cause": "battle",
        "location": "Charleston Harbor, South Carolina",
        "region": "north_atlantic",
        "status": "found",
        "lat": 32.72,
        "lon": -79.79,
        "unc": 0.03,
        "depth": 9,
        "flag": "US",
        "type": "submarine",
        "gp": 1,
    },
    # --- Gold Rush era ---
    {
        "n": 5,
        "ship": "SS Central America",
        "date": "1857-09-12",
        "cause": "storm",
        "location": "Off Cape Hatteras, North Carolina",
        "region": "north_atlantic",
        "status": "found",
        "lat": 31.67,
        "lon": -77.00,
        "unc": 0.5,
        "depth": 2200,
        "flag": "US",
        "type": "steamer",
        "gp": 2,
    },
    # --- World War I ---
    {
        "n": 6,
        "ship": "USS San Diego",
        "date": "1918-07-19",
        "cause": "battle",
        "location": "Off Fire Island, New York",
        "region": "north_atlantic",
        "status": "found",
        "lat": 40.44,
        "lon": -73.08,
        "unc": 0.03,
        "depth": 33,
        "flag": "US",
        "type": "cruiser",
        "gp": 1,
    },
    # --- World War II ---
    {
        "n": 7,
        "ship": "USS Arizona",
        "date": "1941-12-07",
        "cause": "battle",
        "location": "Pearl Harbor, Hawaii",
        "region": "north_pacific",
        "status": "found",
        "lat": 21.37,
        "lon": -157.95,
        "unc": 0.01,
        "depth": 12,
        "flag": "US",
        "type": "battleship",
        "gp": 1,
    },
    {
        "n": 8,
        "ship": "USS Oklahoma",
        "date": "1941-12-07",
        "cause": "battle",
        "location": "Pearl Harbor, Hawaii",
        "region": "north_pacific",
        "status": "found",
        "lat": 21.37,
        "lon": -157.95,
        "unc": 0.01,
        "depth": 14,
        "flag": "US",
        "type": "battleship",
        "gp": 1,
    },
    {
        "n": 9,
        "ship": "USS Yorktown",
        "date": "1942-06-07",
        "cause": "battle",
        "location": "Battle of Midway, Pacific",
        "region": "north_pacific",
        "status": "found",
        "lat": 30.47,
        "lon": -176.64,
        "unc": 0.5,
        "depth": 5186,
        "flag": "US",
        "type": "aircraft carrier",
        "gp": 2,
    },
    {
        "n": 10,
        "ship": "USS Indianapolis",
        "date": "1945-07-30",
        "cause": "battle",
        "location": "Philippine Sea",
        "region": "north_pacific",
        "status": "found",
        "lat": 12.03,
        "lon": 134.82,
        "unc": 1.0,
        "depth": 5500,
        "flag": "US",
        "type": "cruiser",
        "gp": 2,
    },
    {
        "n": 11,
        "ship": "SS Robert E. Lee",
        "date": "1942-07-30",
        "cause": "battle",
        "location": "Off Mississippi Delta, Gulf of Mexico",
        "region": "gulf_of_mexico",
        "status": "found",
        "lat": 28.92,
        "lon": -89.35,
        "unc": 5.0,
        "depth": 55,
        "flag": "US",
        "type": "passenger",
        "gp": 2,
    },
    {
        "n": 12,
        "ship": "SS Alcoa Puritan",
        "date": "1942-05-06",
        "cause": "battle",
        "location": "Gulf of Mexico, off Florida",
        "region": "gulf_of_mexico",
        "status": "found",
        "lat": 25.20,
        "lon": -84.72,
        "unc": 5.0,
        "depth": 82,
        "flag": "US",
        "type": "cargo",
        "gp": 2,
    },
    # --- Great Lakes ---
    {
        "n": 13,
        "ship": "Edmund Fitzgerald",
        "date": "1975-11-10",
        "cause": "storm",
        "location": "Lake Superior",
        "region": "great_lakes",
        "status": "found",
        "lat": 46.99,
        "lon": -85.11,
        "unc": 0.03,
        "depth": 160,
        "flag": "US",
        "type": "bulk carrier",
        "gp": 1,
    },
    {
        "n": 14,
        "ship": "SS Carl D. Bradley",
        "date": "1958-11-18",
        "cause": "storm",
        "location": "Lake Michigan",
        "region": "great_lakes",
        "status": "found",
        "lat": 45.55,
        "lon": -85.55,
        "unc": 0.03,
        "depth": 107,
        "flag": "US",
        "type": "bulk carrier",
        "gp": 1,
    },
    {
        "n": 15,
        "ship": "SS Daniel J. Morrell",
        "date": "1966-11-29",
        "cause": "storm",
        "location": "Lake Huron",
        "region": "great_lakes",
        "status": "found",
        "lat": 44.24,
        "lon": -82.84,
        "unc": 0.03,
        "depth": 65,
        "flag": "US",
        "type": "bulk carrier",
        "gp": 1,
    },
    {
        "n": 16,
        "ship": "SS Eastland",
        "date": "1915-07-24",
        "cause": "grounding",
        "location": "Chicago River, Illinois",
        "region": "great_lakes",
        "status": "found",
        "lat": 41.89,
        "lon": -87.63,
        "unc": 0.01,
        "depth": 6,
        "flag": "US",
        "type": "passenger",
        "gp": 1,
    },
    {
        "n": 17,
        "ship": "Le Griffon",
        "date": "1679-09-18",
        "cause": "storm",
        "location": "Lake Michigan or Lake Huron",
        "region": "great_lakes",
        "status": "unfound",
        "lat": 45.30,
        "lon": -85.50,
        "unc": 200.0,
        "depth": None,
        "flag": "FR",
        "type": "barque",
        "gp": 4,
    },
    # --- Gulf of Mexico ---
    {
        "n": 18,
        "ship": "SS Selma",
        "date": "1922-03-09",
        "cause": "scuttled",
        "location": "Galveston Bay, Texas",
        "region": "gulf_of_mexico",
        "status": "found",
        "lat": 29.34,
        "lon": -94.87,
        "unc": 0.03,
        "depth": 6,
        "flag": "US",
        "type": "tanker",
        "gp": 1,
    },
    {
        "n": 19,
        "ship": "SS Tarpon",
        "date": "1937-08-12",
        "cause": "storm",
        "location": "Gulf of Mexico, off Louisiana",
        "region": "gulf_of_mexico",
        "status": "found",
        "lat": 28.60,
        "lon": -91.40,
        "unc": 5.0,
        "depth": 40,
        "flag": "US",
        "type": "cargo",
        "gp": 2,
    },
    {
        "n": 20,
        "ship": "USS Hatteras",
        "date": "1863-01-11",
        "cause": "battle",
        "location": "Off Galveston, Texas",
        "region": "gulf_of_mexico",
        "status": "found",
        "lat": 29.14,
        "lon": -94.71,
        "unc": 0.1,
        "depth": 17,
        "flag": "US",
        "type": "warship",
        "gp": 1,
    },
    # --- Famous liners ---
    {
        "n": 21,
        "ship": "SS Andrea Doria",
        "date": "1956-07-26",
        "cause": "collision",
        "location": "Off Nantucket, Massachusetts",
        "region": "north_atlantic",
        "status": "found",
        "lat": 40.30,
        "lon": -69.85,
        "unc": 0.03,
        "depth": 75,
        "flag": "IT",
        "type": "liner",
        "gp": 1,
    },
    {
        "n": 22,
        "ship": "SS Republic",
        "date": "1865-10-25",
        "cause": "storm",
        "location": "Off Georgia coast",
        "region": "north_atlantic",
        "status": "found",
        "lat": 31.49,
        "lon": -79.23,
        "unc": 0.5,
        "depth": 518,
        "flag": "US",
        "type": "steamer",
        "gp": 2,
    },
    {
        "n": 23,
        "ship": "SS Portland",
        "date": "1898-11-27",
        "cause": "storm",
        "location": "Off Cape Cod, Massachusetts",
        "region": "north_atlantic",
        "status": "found",
        "lat": 42.26,
        "lon": -70.07,
        "unc": 0.03,
        "depth": 57,
        "flag": "US",
        "type": "passenger",
        "gp": 1,
    },
    # --- Submarines ---
    {
        "n": 24,
        "ship": "USS Thresher",
        "date": "1963-04-10",
        "cause": "unknown",
        "location": "North Atlantic, east of Cape Cod",
        "region": "north_atlantic",
        "status": "found",
        "lat": 41.73,
        "lon": -64.97,
        "unc": 0.5,
        "depth": 2560,
        "flag": "US",
        "type": "submarine",
        "gp": 2,
    },
    {
        "n": 25,
        "ship": "USS Scorpion",
        "date": "1968-05-22",
        "cause": "unknown",
        "location": "Mid-Atlantic, southwest of Azores",
        "region": "north_atlantic",
        "status": "found",
        "lat": 32.92,
        "lon": -33.15,
        "unc": 1.0,
        "depth": 3050,
        "flag": "US",
        "type": "submarine",
        "gp": 2,
    },
    # --- Colonial era ---
    {
        "n": 26,
        "ship": "Henrietta Marie",
        "date": "1700-01-01",
        "cause": "reef",
        "location": "New Ground Reef, Florida Keys",
        "region": "gulf_of_mexico",
        "status": "found",
        "lat": 24.53,
        "lon": -81.80,
        "unc": 0.03,
        "depth": 10,
        "flag": "UK",
        "type": "merchant",
        "gp": 1,
    },
    {
        "n": 27,
        "ship": "Whydah Gally",
        "date": "1717-04-26",
        "cause": "storm",
        "location": "Off Wellfleet, Cape Cod",
        "region": "north_atlantic",
        "status": "found",
        "lat": 41.87,
        "lon": -69.97,
        "unc": 0.03,
        "depth": 5,
        "flag": "UK",
        "type": "galley",
        "gp": 1,
    },
    {
        "n": 28,
        "ship": "Queen Anne's Revenge",
        "date": "1718-06-10",
        "cause": "grounding",
        "location": "Beaufort Inlet, North Carolina",
        "region": "north_atlantic",
        "status": "found",
        "lat": 34.69,
        "lon": -76.63,
        "unc": 0.01,
        "depth": 7,
        "flag": "UK",
        "type": "frigate",
        "gp": 1,
    },
    {
        "n": 29,
        "ship": "San Esteban",
        "date": "1554-04-29",
        "cause": "storm",
        "location": "Padre Island, Texas",
        "region": "gulf_of_mexico",
        "status": "found",
        "lat": 26.55,
        "lon": -97.30,
        "unc": 1.0,
        "depth": 4,
        "flag": "ES",
        "type": "galleon",
        "gp": 2,
    },
    {
        "n": 30,
        "ship": "Nuestra Senora de Atocha",
        "date": "1622-09-06",
        "cause": "storm",
        "location": "Florida Keys",
        "region": "gulf_of_mexico",
        "status": "found",
        "lat": 24.52,
        "lon": -82.18,
        "unc": 0.03,
        "depth": 16,
        "flag": "ES",
        "type": "galleon",
        "gp": 1,
    },
    # --- Pacific wrecks ---
    {
        "n": 31,
        "ship": "SS Brother Jonathan",
        "date": "1865-07-30",
        "cause": "reef",
        "location": "St George Reef, California",
        "region": "north_pacific",
        "status": "found",
        "lat": 41.84,
        "lon": -124.37,
        "unc": 0.1,
        "depth": 84,
        "flag": "US",
        "type": "steamer",
        "gp": 1,
    },
    {
        "n": 32,
        "ship": "SS Valencia",
        "date": "1906-01-22",
        "cause": "reef",
        "location": "Off Vancouver Island (near US waters)",
        "region": "north_pacific",
        "status": "found",
        "lat": 48.65,
        "lon": -124.93,
        "unc": 0.1,
        "depth": 20,
        "flag": "US",
        "type": "passenger",
        "gp": 2,
    },
    {
        "n": 33,
        "ship": "SS Montebello",
        "date": "1941-12-23",
        "cause": "battle",
        "location": "Off Cambria, California",
        "region": "north_pacific",
        "status": "found",
        "lat": 35.52,
        "lon": -121.25,
        "unc": 0.1,
        "depth": 274,
        "flag": "US",
        "type": "tanker",
        "gp": 1,
    },
    # --- Tankers and cargo ---
    {
        "n": 34,
        "ship": "SS Marine Electric",
        "date": "1983-02-12",
        "cause": "storm",
        "location": "Off Chincoteague, Virginia",
        "region": "north_atlantic",
        "status": "found",
        "lat": 37.82,
        "lon": -75.09,
        "unc": 0.03,
        "depth": 37,
        "flag": "US",
        "type": "cargo",
        "gp": 1,
    },
    {
        "n": 35,
        "ship": "SS El Faro",
        "date": "2015-10-01",
        "cause": "storm",
        "location": "Near Crooked Island, Bahamas",
        "region": "north_atlantic",
        "status": "found",
        "lat": 23.38,
        "lon": -73.87,
        "unc": 0.03,
        "depth": 4572,
        "flag": "US",
        "type": "cargo",
        "gp": 1,
    },
    {
        "n": 36,
        "ship": "SS Pendleton",
        "date": "1952-02-18",
        "cause": "storm",
        "location": "Off Chatham, Cape Cod",
        "region": "north_atlantic",
        "status": "found",
        "lat": 41.62,
        "lon": -69.88,
        "unc": 0.03,
        "depth": 21,
        "flag": "US",
        "type": "tanker",
        "gp": 1,
    },
    # --- Fishing vessels ---
    {
        "n": 37,
        "ship": "Andrea Gail",
        "date": "1991-10-28",
        "cause": "storm",
        "location": "Georges Bank, North Atlantic",
        "region": "north_atlantic",
        "status": "unfound",
        "lat": 44.00,
        "lon": -56.50,
        "unc": 200.0,
        "depth": None,
        "flag": "US",
        "type": "fishing",
        "gp": 4,
    },
    # --- U-boat victims (East Coast) ---
    {
        "n": 38,
        "ship": "SS Dixie Arrow",
        "date": "1942-03-26",
        "cause": "battle",
        "location": "Off Cape Hatteras, North Carolina",
        "region": "north_atlantic",
        "status": "found",
        "lat": 35.08,
        "lon": -75.72,
        "unc": 0.1,
        "depth": 27,
        "flag": "US",
        "type": "tanker",
        "gp": 1,
    },
    {
        "n": 39,
        "ship": "SS David H. Atwater",
        "date": "1942-04-02",
        "cause": "battle",
        "location": "Off Virginia Beach",
        "region": "north_atlantic",
        "status": "found",
        "lat": 36.80,
        "lon": -75.80,
        "unc": 5.0,
        "depth": 23,
        "flag": "US",
        "type": "cargo",
        "gp": 2,
    },
    # --- Revolutionary War era ---
    {
        "n": 40,
        "ship": "HMS DeBraak",
        "date": "1798-05-25",
        "cause": "storm",
        "location": "Off Cape Henlopen, Delaware",
        "region": "north_atlantic",
        "status": "found",
        "lat": 38.78,
        "lon": -75.08,
        "unc": 0.03,
        "depth": 24,
        "flag": "UK",
        "type": "warship",
        "gp": 1,
    },
    {
        "n": 41,
        "ship": "Bonhomme Richard",
        "date": "1779-09-25",
        "cause": "battle",
        "location": "Off Flamborough Head (US-built)",
        "region": "north_atlantic",
        "status": "unfound",
        "lat": 54.10,
        "lon": -0.10,
        "unc": 50.0,
        "depth": None,
        "flag": "US",
        "type": "warship",
        "gp": 3,
    },
    # --- More Gulf wrecks ---
    {
        "n": 42,
        "ship": "SS Coimbra",
        "date": "1942-01-15",
        "cause": "battle",
        "location": "Off Long Island, New York",
        "region": "north_atlantic",
        "status": "found",
        "lat": 40.49,
        "lon": -72.05,
        "unc": 0.03,
        "depth": 55,
        "flag": "UK",
        "type": "tanker",
        "gp": 1,
    },
    {
        "n": 43,
        "ship": "Heroine",
        "date": "1838-08-01",
        "cause": "storm",
        "location": "Red River, Oklahoma",
        "region": "gulf_of_mexico",
        "status": "found",
        "lat": 33.95,
        "lon": -95.35,
        "unc": 0.1,
        "depth": 3,
        "flag": "US",
        "type": "steamer",
        "gp": 2,
    },
    # --- Deep wrecks ---
    {
        "n": 44,
        "ship": "SS Robert E. Lee",
        "date": "1942-07-30",
        "cause": "battle",
        "location": "Off Mississippi Delta",
        "region": "gulf_of_mexico",
        "status": "found",
        "lat": 28.92,
        "lon": -89.35,
        "unc": 5.0,
        "depth": 55,
        "flag": "US",
        "type": "passenger",
        "gp": 2,
    },
    # --- Low quality / approximate ---
    {
        "n": 45,
        "ship": "Unknown schooner",
        "date": None,
        "cause": "unknown",
        "location": None,
        "region": "north_atlantic",
        "status": "approximate",
        "lat": 42.10,
        "lon": -70.30,
        "unc": 500.0,
        "depth": None,
        "flag": None,
        "type": None,
        "gp": 4,
    },
    {
        "n": 46,
        "ship": "Unknown barge",
        "date": None,
        "cause": "unknown",
        "location": None,
        "region": "north_pacific",
        "status": "approximate",
        "lat": 47.60,
        "lon": -124.50,
        "unc": 500.0,
        "depth": None,
        "flag": None,
        "type": None,
        "gp": 4,
    },
    {
        "n": 47,
        "ship": "SS Caribsea",
        "date": "1942-03-11",
        "cause": "battle",
        "location": "Off Cape Lookout, North Carolina",
        "region": "north_atlantic",
        "status": "found",
        "lat": 34.63,
        "lon": -76.63,
        "unc": 0.1,
        "depth": 27,
        "flag": "US",
        "type": "cargo",
        "gp": 1,
    },
    {
        "n": 48,
        "ship": "SS City of Austin",
        "date": "1967-08-10",
        "cause": "grounding",
        "location": "Padre Island, Texas",
        "region": "gulf_of_mexico",
        "status": "found",
        "lat": 26.10,
        "lon": -97.17,
        "unc": 0.1,
        "depth": 3,
        "flag": "US",
        "type": "cargo",
        "gp": 2,
    },
    {
        "n": 49,
        "ship": "SS Oregon",
        "date": "1886-03-14",
        "cause": "collision",
        "location": "Off Fire Island, New York",
        "region": "north_atlantic",
        "status": "found",
        "lat": 40.44,
        "lon": -73.11,
        "unc": 0.03,
        "depth": 40,
        "flag": "US",
        "type": "liner",
        "gp": 1,
    },
    {
        "n": 50,
        "ship": "Sultana",
        "date": "1865-04-27",
        "cause": "fire",
        "location": "Mississippi River, near Memphis",
        "region": "gulf_of_mexico",
        "status": "approximate",
        "lat": 35.15,
        "lon": -90.01,
        "unc": 50.0,
        "depth": None,
        "flag": "US",
        "type": "steamer",
        "gp": 3,
    },
]


def build_wrecks() -> list[dict]:
    """Convert raw wreck data to standard format."""
    wrecks = []
    for w in WRECKS_RAW:
        wreck_id = f"{ARCHIVE}_wreck:{w['n']:05d}"
        position = {
            "lat": w["lat"],
            "lon": w["lon"],
            "uncertainty_km": w["unc"],
        }
        rec = {
            "wreck_id": wreck_id,
            "ship_name": w["ship"],
            "loss_date": w["date"],
            "loss_cause": w["cause"],
            "loss_location": w["location"],
            "region": w["region"],
            "status": w["status"],
            "position": position,
            "depth_estimate_m": w["depth"],
            "flag": w["flag"],
            "vessel_type": w["type"],
            "gp_quality": w["gp"],
            "archive": ARCHIVE,
        }
        wrecks.append(rec)
    return wrecks


def main() -> None:
    args = parse_args("Generate NOAA curated wreck data (fallback subset)")

    if not args.force and is_cached(WRECKS_OUTPUT, args.cache_max_age):
        print(f"  {WRECKS_OUTPUT.name} is up to date (use --force to regenerate)")
        return

    wrecks = build_wrecks()

    # Validate IDs
    expected_ids = {f"{ARCHIVE}_wreck:{i:05d}" for i in range(1, len(wrecks) + 1)}
    actual_ids = {w["wreck_id"] for w in wrecks}
    assert expected_ids == actual_ids, f"ID mismatch: {expected_ids - actual_ids}"

    for w in wrecks:
        assert w["archive"] == ARCHIVE

    save_json(wrecks, WRECKS_OUTPUT.name)
    print(f"  Generated {len(wrecks)} NOAA curated wrecks")


if __name__ == "__main__":
    main()
